using System;
using System.Collections.Generic;

namespace Lib.CliSitef.ConstantValues
{
    public class BandeiraPadraoConst
    {
        public string Codigo { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }

        public int CodigoInt
        {
            get
            {
                return string.IsNullOrWhiteSpace(Codigo) ? 0 : Convert.ToInt32(Codigo);
            }
        }
        public string NomeTipoCodigo
        {
            get
            {
                return string.IsNullOrWhiteSpace(Nome) ? "" : Nome + "|" + Tipo + "|" + Codigo;
            }
        }
    }

    public class BandeiraPadrao
    {
        public static List<BandeiraPadraoConst> RetornarLista()
        {
            return new List<BandeiraPadraoConst>()
            {
                new BandeiraPadraoConst() { Nome = "VISA", Tipo = "CREDITO", Codigo = "00001"},
                new BandeiraPadraoConst() { Nome = "VISA", Tipo = "DEBITO", Codigo = "20002"},
                new BandeiraPadraoConst() { Nome = "VISA", Tipo = "VOUCHER", Codigo = "10002"},
                new BandeiraPadraoConst() { Nome = "MASTER", Tipo = "CREDITO", Codigo = "00002"},
                new BandeiraPadraoConst() { Nome = "MASTER", Tipo = "DEBITO", Codigo = "20001"},
                new BandeiraPadraoConst() { Nome = "HIPER", Tipo = "CREDITO", Codigo = "00012"},
                new BandeiraPadraoConst() { Nome = "HIPER", Tipo = "DEBITO", Codigo = "20037"},
                new BandeiraPadraoConst() { Nome = "SOROCRED", Tipo = "CREDITO", Codigo = "00015"},
                new BandeiraPadraoConst() { Nome = "SOROCRED", Tipo = "VOUCHER", Codigo = "10037"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "DEBITO", Codigo = "20003"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "VOUCHER", Codigo = "10012"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "CREDITO", Codigo = "00030"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "VOUCHER", Codigo = "10001"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "VOUCHER REFEICAO", Codigo = "10024"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10025"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "VOUCHER CULTURA", Codigo = "10027"},
                new BandeiraPadraoConst() { Nome = "TICKET COMBUSTIVEL", Codigo = "10054"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "CREDITO", Codigo = "10003"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "VOUCHER REFEICAO", Codigo = "10028"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10029"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "GIFT", Codigo = "10030"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "VOUCHER", Codigo = "10031"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "VOUCHER CULTURA", Codigo = "10032"},
                new BandeiraPadraoConst() { Nome = "SODEXO COMBUSTIVEL", Codigo = "10033"},
                new BandeiraPadraoConst() { Nome = "NUTRICASH", Tipo = "VOUCHER", Codigo = "10004"},
                new BandeiraPadraoConst() { Nome = "NUTRICASH", Tipo = "VOUCHER CULTURA", Codigo = "10053"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER", Codigo = "10006"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER CULTURA", Codigo = "10051"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "VOUCHER", Codigo = "10011"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "VOUCHER CULTURA", Codigo = "10055"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "VOUCHER", Codigo = "10019"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "VOUCHER REFEICAO", Codigo = "10021"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "VOUCHER CULTURA", Codigo = "10023"},
                new BandeiraPadraoConst() { Nome = "ELO", Tipo = "CREDITO", Codigo = "00031"},
                new BandeiraPadraoConst() { Nome = "ELO", Tipo = "DEBITO", Codigo = "20032"},
                new BandeiraPadraoConst() { Nome = "SICREDI", Tipo = "CREDITO", Codigo = "00041"},
                new BandeiraPadraoConst() { Nome = "SICREDI", Tipo = "DEBITO", Codigo = "20042"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "CREDITO", Codigo = "00033"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "DEBITO", Codigo = "20034"},
                new BandeiraPadraoConst() { Nome = "BANESCARD", Tipo = "CREDITO", Codigo = "00035"},
                new BandeiraPadraoConst() { Nome = "BANESCARD", Tipo = "DEBITO", Codigo = "20036"},
                new BandeiraPadraoConst() { Nome = "VEROCHEQUE", Tipo = "VOUCHER", Codigo = "10008"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "CREDITO", Codigo = "00043"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "VOUCHER", Codigo = "10044"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "VOUCHER CULTURA", Codigo = "10056"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "VOUCHER REFEICAO", Codigo = "10047"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10048"},
                new BandeiraPadraoConst() { Nome = "VR COMBUSTIVEL", Codigo = "10049"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "VOUCHER CULTURA", Codigo = "10050"},
                new BandeiraPadraoConst() { Nome = "PAO DE ACUCAR", Tipo = "CREDITO", Codigo = "00009"},
                new BandeiraPadraoConst() { Nome = "DINERS", Tipo = "VOUCHER", Codigo = "10014"},
                new BandeiraPadraoConst() { Nome = "CETELEM", Tipo = "CREDITO", Codigo = "00038"},
                new BandeiraPadraoConst() { Nome = "DINERS", Tipo = "CREDITO", Codigo = "00003"},
                new BandeiraPadraoConst() { Nome = "AMEX", Tipo = "CREDITO", Codigo = "00004"},
                new BandeiraPadraoConst() { Nome = "SIDECARD", Tipo = "CREDITO", Codigo = "00006"},
                new BandeiraPadraoConst() { Nome = "FINIVEST", Tipo = "CREDITO", Codigo = "00010"},
                new BandeiraPadraoConst() { Nome = "JCB", Tipo = "CREDITO", Codigo = "00011"},
                new BandeiraPadraoConst() { Nome = "VALEMULTI", Tipo = "VOUCHER", Codigo = "10039"},
                new BandeiraPadraoConst() { Nome = "VALEFROTA", Tipo = "VOUCHER", Codigo = "10040"},
                new BandeiraPadraoConst() { Nome = "AVISTA", Tipo = "CREDITO", Codigo = "00045"},
                new BandeiraPadraoConst() { Nome = "MAIS", Tipo = "CREDITO", Codigo = "00057"},
                new BandeiraPadraoConst() { Nome = "CREDZ", Tipo = "CREDITO", Codigo = "00070"},
                new BandeiraPadraoConst() { Nome = "AURA", Tipo = "CREDITO", Codigo = "00013"},
                new BandeiraPadraoConst() { Nome = "BANQUET", Tipo = "VOUCHER", Codigo = "10007"},
                new BandeiraPadraoConst() { Nome = "SAPORE", Tipo = "VOUCHER", Codigo = "10009"},
                new BandeiraPadraoConst() { Nome = "BNBCLUBE", Tipo = "VOUCHER", Codigo = "10010"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "VOUCHER", Codigo = "10005"},
                new BandeiraPadraoConst() { Nome = "REFEISUL", Tipo = "VOUCHER CULTURA", Codigo = "10052"},
                new BandeiraPadraoConst() { Nome = "BANPARA", Tipo = "CREDITO", Codigo = "00058"},
                new BandeiraPadraoConst() { Nome = "BANPARA", Tipo = "DEBITO", Codigo = "20059"},
                new BandeiraPadraoConst() { Nome = "AMAZONCARD", Tipo = "CREDITO", Codigo = "00060"},
                new BandeiraPadraoConst() { Nome = "YAMADA", Tipo = "CREDITO", Codigo = "00061"},
                new BandeiraPadraoConst() { Nome = "GOIASCARD", Tipo = "CREDITO", Codigo = "00062"},
                new BandeiraPadraoConst() { Nome = "CREDPAR", Tipo = "CREDITO", Codigo = "00063"},
                new BandeiraPadraoConst() { Nome = "BOTICARIO", Tipo = "CREDITO", Codigo = "00064"},
                new BandeiraPadraoConst() { Nome = "ASCARD", Tipo = "CREDITO", Codigo = "00065"},
                new BandeiraPadraoConst() { Nome = "JETPAR", Tipo = "CREDITO", Codigo = "00066"},
                new BandeiraPadraoConst() { Nome = "MAXXCARD", Tipo = "CREDITO", Codigo = "00067"},
                new BandeiraPadraoConst() { Nome = "GARANTIDO", Tipo = "CREDITO", Codigo = "00068"},
                new BandeiraPadraoConst() { Nome = "AMAZONPRIME", Tipo = "CREDITO", Codigo = "00069"},
                new BandeiraPadraoConst() { Nome = "LOSANGO", Tipo = "CREDITO", Codigo = "00014"},
                new BandeiraPadraoConst() { Nome = "REDESHOP", Tipo = "CREDITO", Codigo = "00008"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "VOUCHER BENEFICIO", Codigo = "10070"},
                new BandeiraPadraoConst() { Nome = "PLANVALE COMBUSTIVEL", Codigo = "10074"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10072"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER REFEICAO", Codigo = "10073"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER FARMACIA", Codigo = "10075"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER BENEFICIO", Codigo = "10071"},
                new BandeiraPadraoConst() { Nome = "CALCARD", Tipo = "CREDITO", Codigo = "00090"},
                new BandeiraPadraoConst() { Nome = "ACCENTIV", Tipo = "CREDITO", Codigo = "00107"},
                new BandeiraPadraoConst() { Nome = "ASPEB", Tipo = "CREDITO", Codigo = "00108"},
                new BandeiraPadraoConst() { Nome = "VALE EXPRESS", Tipo = "CREDITO", Codigo = "00109"},
                new BandeiraPadraoConst() { Nome = "VALE EXPRESS", Tipo = "VOUCHER", Codigo = "10110"},
                new BandeiraPadraoConst() { Nome = "VALE EXPRESS", Tipo = "DEBITO", Codigo = "20111"},
                new BandeiraPadraoConst() { Nome = "GOLDICARD COMBUSTIVEL", Codigo = "10112"},
                new BandeiraPadraoConst() { Nome = "FLEETCARD COMBUSTIVEL", Codigo = "10113"},
                new BandeiraPadraoConst() { Nome = "DAYCARD", Tipo = "CREDITO", Codigo = "00114"},
                new BandeiraPadraoConst() { Nome = "DAYCARD", Tipo = "DEBITO", Codigo = "20115"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "CREDITO", Codigo = "00130"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "DEBITO", Codigo = "20131"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "VOUCHER", Codigo = "10132"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "VOUCHER REFEICAO", Codigo = "10133"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10134"},
                new BandeiraPadraoConst() { Nome = "GOODCARD COMBUSTIVEL", Codigo = "10135"},
                new BandeiraPadraoConst() { Nome = "PAGSIMPLES", Tipo = "CREDITO", Codigo = "00131"},
                new BandeiraPadraoConst() { Nome = "ICARDS", Tipo = "CREDITO", Codigo = "00132"},
                new BandeiraPadraoConst() { Nome = "TRICARD", Tipo = "CREDITO", Codigo = "00093"},
                new BandeiraPadraoConst() { Nome = "TRICARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00094"},
                new BandeiraPadraoConst() { Nome = "CREDISHOP", Tipo = "CREDITO", Codigo = "00071"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "CREDITO", Codigo = "00072"},
                new BandeiraPadraoConst() { Nome = "LIBERCARD", Tipo = "CREDITO", Codigo = "00073"},
                new BandeiraPadraoConst() { Nome = "PEELA", Tipo = "CREDITO", Codigo = "00078"},
                new BandeiraPadraoConst() { Nome = "BANRISUL", Tipo = "CREDITO", Codigo = "00084"},
                new BandeiraPadraoConst() { Nome = "VERDECARD", Tipo = "CREDITO", Codigo = "00086"},
                new BandeiraPadraoConst() { Nome = "VERDECARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00086"},
                new BandeiraPadraoConst() { Nome = "REFEISUL", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00087"},
                new BandeiraPadraoConst() { Nome = "BANESE", Tipo = "CREDITO", Codigo = "00091"},
                new BandeiraPadraoConst() { Nome = "APOLOCARD", Tipo = "CREDITO", Codigo = "00095"},
                new BandeiraPadraoConst() { Nome = "GLOBALCOOPER", Tipo = "CREDITO", Codigo = "00096"},
                new BandeiraPadraoConst() { Nome = "PRATI", Tipo = "CREDITO", Codigo = "00097"},
                new BandeiraPadraoConst() { Nome = "SUPPERCARD", Tipo = "CREDITO", Codigo = "00098"},
                new BandeiraPadraoConst() { Nome = "QUALITA", Tipo = "CREDITO", Codigo = "00099"},
                new BandeiraPadraoConst() { Nome = "TECBIZ", Tipo = "CREDITO", Codigo = "00101"},
                new BandeiraPadraoConst() { Nome = "TODO", Tipo = "CREDITO", Codigo = "00102"},
                new BandeiraPadraoConst() { Nome = "VECELLCARD", Tipo = "CREDITO", Codigo = "00104"},
                new BandeiraPadraoConst() { Nome = "MAXXVAN", Tipo = "CREDITO", Codigo = "00105"},
                new BandeiraPadraoConst() { Nome = "RVCARDS", Tipo = "CREDITO", Codigo = "00118"},
                new BandeiraPadraoConst() { Nome = "LEADER", Tipo = "CREDITO", Codigo = "00119"},
                new BandeiraPadraoConst() { Nome = "TELENET", Tipo = "CREDITO", Codigo = "00121"},
                new BandeiraPadraoConst() { Nome = "TICKETLOG", Tipo = "CREDITO", Codigo = "00124"},
                new BandeiraPadraoConst() { Nome = "SOFTNEX", Tipo = "CREDITO", Codigo = "00127"},
                new BandeiraPadraoConst() { Nome = "VALEFACIL", Tipo = "VOUCHER", Codigo = "10046"},
                new BandeiraPadraoConst() { Nome = "PEELA", Tipo = "GIFT", Codigo = "10076"},
                new BandeiraPadraoConst() { Nome = "LIBERCARD", Tipo = "VOUCHER", Codigo = "10077"},
                new BandeiraPadraoConst() { Nome = "ALELO COMBUSTIVEL", Codigo = "10082"},
                new BandeiraPadraoConst() { Nome = "ELO COMBUSTIVEL", Codigo = "10082"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "VOUCHER", Codigo = "10083"},
                new BandeiraPadraoConst() { Nome = "REFEISUL COMBUSTIVEL", Codigo = "10088"},
                new BandeiraPadraoConst() { Nome = "REFEISUL", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10089"},
                new BandeiraPadraoConst() { Nome = "VEROCHEQUE", Tipo = "VOUCHER CULTURA", Codigo = "10090"},
                new BandeiraPadraoConst() { Nome = "QUALITA", Tipo = "GIFT", Codigo = "10100"},
                new BandeiraPadraoConst() { Nome = "TODO", Tipo = "GIFT", Codigo = "10103"},
                new BandeiraPadraoConst() { Nome = "HUBPREPAID", Tipo = "VOUCHER", Codigo = "10116"},
                new BandeiraPadraoConst() { Nome = "FLEXFROTA COMBUSTIVEL", Codigo = "10117"},
                new BandeiraPadraoConst() { Nome = "TELENET", Tipo = "VOUCHER", Codigo = "10122"},
                new BandeiraPadraoConst() { Nome = "TELENET COMBUSTIVEL", Codigo = "10123"},
                new BandeiraPadraoConst() { Nome = "TICKETLOG COMBUSTIVEL", Codigo = "10125"},
                new BandeiraPadraoConst() { Nome = "SOFTNEX", Tipo = "VOUCHER", Codigo = "10129"},
                new BandeiraPadraoConst() { Nome = "SOFTNEX", Tipo = "DEBITO", Codigo = "20128"},
                new BandeiraPadraoConst() { Nome = "VELOE COMBUSTIVEL", Codigo = "10136"},
                new BandeiraPadraoConst() { Nome = "SOROCRED", Tipo = "DEBITO", Codigo = "20071"},
                new BandeiraPadraoConst() { Nome = "MAXXICARD", Tipo = "DEBITO", Codigo = "20072"},
                new BandeiraPadraoConst() { Nome = "MAXXICARD", Tipo = "CREDITO", Codigo = "20073"},
                new BandeiraPadraoConst() { Nome = "MAXXICARD", Tipo = "GIFT", Codigo = "20074"},
                new BandeiraPadraoConst() { Nome = "MAXXICARD COMBUSTIVEL", Codigo = "20075"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "DEBITO", Codigo = "20076"},
                new BandeiraPadraoConst() { Nome = "BANRISUL", Tipo = "DEBITO", Codigo = "20085"},
                new BandeiraPadraoConst() { Nome = "BANESE", Tipo = "DEBITO", Codigo = "20092"},
                new BandeiraPadraoConst() { Nome = "MAXXVAN", Tipo = "DEBITO", Codigo = "20106"},
                new BandeiraPadraoConst() { Nome = "CONVENIOFACIL", Tipo = "CREDITO", Codigo = "20120"},
                new BandeiraPadraoConst() { Nome = "TICKETLOG", Tipo = "DEBITO", Codigo = "20126"},
                new BandeiraPadraoConst() { Nome = "FORTBRASIL", Tipo = "CREDITO", Codigo = "00137"},
                new BandeiraPadraoConst() { Nome = "VOXCRED", Tipo = "CREDITO", Codigo = "00138"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10137"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "DEBITO", Codigo = "20132"},
                new BandeiraPadraoConst() { Nome = "WIZEO COMBUSTIVEL", Codigo = "10139"},
                new BandeiraPadraoConst() { Nome = "BORBANET", Tipo = "CREDITO", Codigo = "00140"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "VOUCHER REFEICAO", Codigo = "10138"},
                new BandeiraPadraoConst() { Nome = "BEN VISAVALE", Tipo = "VOUCHER REFEICAO", Codigo = "10140"},
                new BandeiraPadraoConst() { Nome = "BEN VISAVALE", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10141"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10022"},
                new BandeiraPadraoConst() { Nome = "ABRAPETITE", Tipo = "VOUCHER", Codigo = "10142"},
                new BandeiraPadraoConst() { Nome = "AVANCARD", Tipo = "VOUCHER", Codigo = "10143"},
                new BandeiraPadraoConst() { Nome = "BIGCARD", Tipo = "CREDITO", Codigo = "00142"},
                new BandeiraPadraoConst() { Nome = "BIQ", Tipo = "VOUCHER", Codigo = "10144"},
                new BandeiraPadraoConst() { Nome = "BONUSCRED", Tipo = "CREDITO", Codigo = "00143"},
                new BandeiraPadraoConst() { Nome = "BONUSCRED", Tipo = "VOUCHER", Codigo = "10146"},
                new BandeiraPadraoConst() { Nome = "BRASIL CARD", Tipo = "CREDITO", Codigo = "00144"},
                new BandeiraPadraoConst() { Nome = "BRASIL CARD", Tipo = "VOUCHER", Codigo = "10146"},
                new BandeiraPadraoConst() { Nome = "CONVENIOS CARD", Tipo = "CREDITO", Codigo = "00145"},
                new BandeiraPadraoConst() { Nome = "CONVENIOS CARD", Tipo = "VOUCHER", Codigo = "10147"},
                new BandeiraPadraoConst() { Nome = "CREDIALIMENTACAO", Tipo = "VOUCHER", Codigo = "10149"},
                new BandeiraPadraoConst() { Nome = "DIAMANTE CARD", Tipo = "CREDITO", Codigo = "00147"},
                new BandeiraPadraoConst() { Nome = "EUCARD", Tipo = "VOUCHER", Codigo = "10150"},
                new BandeiraPadraoConst() { Nome = "FACECARD", Tipo = "VOUCHER", Codigo = "10151"},
                new BandeiraPadraoConst() { Nome = "FLEETCARD", Tipo = "VOUCHER", Codigo = "10152"},
                new BandeiraPadraoConst() { Nome = "FORTCARD", Tipo = "CREDITO", Codigo = "00148"},
                new BandeiraPadraoConst() { Nome = "JET CARD", Tipo = "CREDITO", Codigo = "00149"},
                new BandeiraPadraoConst() { Nome = "LECARD", Tipo = "VOUCHER", Codigo = "10153"},
                new BandeiraPadraoConst() { Nome = "NUTRICARD", Tipo = "VOUCHER", Codigo = "10154"},
                new BandeiraPadraoConst() { Nome = "ONECARD", Tipo = "CREDITO", Codigo = "00150"},
                new BandeiraPadraoConst() { Nome = "PERSONALCARD", Tipo = "CREDITO", Codigo = "00151"},
                new BandeiraPadraoConst() { Nome = "SENFF", Tipo = "CREDITO", Codigo = "10155"},
                new BandeiraPadraoConst() { Nome = "SINDPLUS", Tipo = "VOUCHER", Codigo = "10156"},
                new BandeiraPadraoConst() { Nome = "SYSTEM FARMA", Tipo = "CREDITO", Codigo = "00152"},
                new BandeiraPadraoConst() { Nome = "USECRED", Tipo = "VOUCHER", Codigo = "10157"},
                new BandeiraPadraoConst() { Nome = "VALESHOP", Tipo = "VOUCHER", Codigo = "10158"},
                new BandeiraPadraoConst() { Nome = "VEGASCARD", Tipo = "VOUCHER", Codigo = "10159"},
                new BandeiraPadraoConst() { Nome = "VS CARD", Tipo = "VOUCHER", Codigo = "10160"},
                new BandeiraPadraoConst() { Nome = "VEGASCARD", Tipo = "CREDITO", Codigo = "00141"},
                new BandeiraPadraoConst() { Nome = "VEGASCARD", Tipo = "DEBITO", Codigo = "20133"},
                new BandeiraPadraoConst() { Nome = "LIV", Tipo = "CREDITO", Codigo = "00153"},
                new BandeiraPadraoConst() { Nome = "LIV", Tipo = "DEBITO", Codigo = "20134"},
                new BandeiraPadraoConst() { Nome = "ROTACARD COMBUSTIVEL", Codigo = "10161"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "VOUCHER", Codigo = "10162"},
                new BandeiraPadraoConst() { Nome = "POLICARD COMBUSTIVEL FROTA", Codigo = "10163"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10164"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "VOUCHER REFEICAO", Codigo = "10165"},
                new BandeiraPadraoConst() { Nome = "COOPELIFE", Tipo = "CREDITO", Codigo = "00155"},
                new BandeiraPadraoConst() { Nome = "COOPELIFE", Tipo = "DEBITO", Codigo = "20136"},
                new BandeiraPadraoConst() { Nome = "SENFF", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10169"},
                new BandeiraPadraoConst() { Nome = "SENFF", Tipo = "VOUCHER REFEICAO", Codigo = "10170"},
                new BandeiraPadraoConst() { Nome = "SENFF", Tipo = "VOUCHER", Codigo = "10171"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10173"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "VOUCHER REFEICAO", Codigo = "10174"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "VOUCHER CULTURA", Codigo = "10175"},
                new BandeiraPadraoConst() { Nome = "VEROCHEQUE", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10176"},
                new BandeiraPadraoConst() { Nome = "VEROCHEQUE", Tipo = "VOUCHER REFEICAO", Codigo = "10177"},
                new BandeiraPadraoConst() { Nome = "TELENET", Tipo = "DEBITO", Codigo = "20137"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "GIFT", Codigo = "10172"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "GIFT", Codigo = "10168"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "VOUCHER CULTURA", Codigo = "10178"},
                new BandeiraPadraoConst() { Nome = "POLICARD COMBUSTIVEL", Codigo = "10179"},
                new BandeiraPadraoConst() { Nome = "SINDSPAM", Tipo = "CREDITO", Codigo = "00156"},
                new BandeiraPadraoConst() { Nome = "SINDSPAM", Tipo = "DEBITO", Codigo = "20138"},
                new BandeiraPadraoConst() { Nome = "PERSONALIDADE CARD", Tipo = "CREDITO", Codigo = "00157"},
                new BandeiraPadraoConst() { Nome = "RG CARD", Tipo = "CREDITO", Codigo = "00158"},
                new BandeiraPadraoConst() { Nome = "TAURUS CARD", Tipo = "CREDITO", Codigo = "00159"},
                new BandeiraPadraoConst() { Nome = "FACILCARD", Tipo = "CREDITO", Codigo = "00160"},
                new BandeiraPadraoConst() { Nome = "ALGORIX", Tipo = "CREDITO", Codigo = "00161"},
                new BandeiraPadraoConst() { Nome = "ALGORIX", Tipo = "DEBITO", Codigo = "20139"},
                new BandeiraPadraoConst() { Nome = "VALESHOP COMBUSTIVEL", Codigo = "10180"},
                new BandeiraPadraoConst() { Nome = "PRIVATE LABEL GENERICO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00007"},
                new BandeiraPadraoConst() { Nome = "CARREFOUR", Tipo = "CREDITO", Codigo = "00164"},
                new BandeiraPadraoConst() { Nome = "ATACADAO", Tipo = "CREDITO", Codigo = "00163"},
                new BandeiraPadraoConst() { Nome = "PORTALCARD", Tipo = "CREDITO", Codigo = "00165"},
                new BandeiraPadraoConst() { Nome = "PORTALCARD", Tipo = "DEBITO", Codigo = "20140"},
                new BandeiraPadraoConst() { Nome = "PORTALCARD COMBUSTIVEL", Codigo = "10181"},
                new BandeiraPadraoConst() { Nome = "AVBR", Tipo = "CREDITO", Codigo = "00166"},
                new BandeiraPadraoConst() { Nome = "VUON", Tipo = "CREDITO", Codigo = "00167"},
                new BandeiraPadraoConst() { Nome = "CREDCESTA", Tipo = "CREDITO", Codigo = "00168"},
                new BandeiraPadraoConst() { Nome = "MARKETPAY", Tipo = "CREDITO", Codigo = "00169"},
                new BandeiraPadraoConst() { Nome = "PERSONALCARD", Tipo = "DEBITO", Codigo = "20141"},
                new BandeiraPadraoConst() { Nome = "PERSONALCARD", Tipo = "VOUCHER", Codigo = "10182"},
                new BandeiraPadraoConst() { Nome = "LIFECARD", Tipo = "CREDITO", Codigo = "00170"},
                new BandeiraPadraoConst() { Nome = "LIFECARD", Tipo = "DEBITO", Codigo = "20142"},
                new BandeiraPadraoConst() { Nome = "LIFECARD", Tipo = "VOUCHER", Codigo = "10183"},
                new BandeiraPadraoConst() { Nome = "TRIOCARD", Tipo = "CREDITO", Codigo = "00171"},
                new BandeiraPadraoConst() { Nome = "TRIOCARD", Tipo = "DEBITO", Codigo = "20143"},
                new BandeiraPadraoConst() { Nome = "TRIOCARD", Tipo = "VOUCHER", Codigo = "10184"},
                new BandeiraPadraoConst() { Nome = "ACCREDITO", Tipo = "CREDITO", Codigo = "00172"},
                new BandeiraPadraoConst() { Nome = "ACCREDITO", Tipo = "DEBITO", Codigo = "20144"},
                new BandeiraPadraoConst() { Nome = "ACCREDITO", Tipo = "VOUCHER", Codigo = "10185"},
                new BandeiraPadraoConst() { Nome = "BNBCLUBE", Tipo = "CREDITO", Codigo = "00173"},
                new BandeiraPadraoConst() { Nome = "BNBCLUBE", Tipo = "DEBITO", Codigo = "20145"},
                new BandeiraPadraoConst() { Nome = "BRASIL CONVENIOS", Tipo = "CREDITO", Codigo = "00174"},
                new BandeiraPadraoConst() { Nome = "BRASIL CONVENIOS", Tipo = "DEBITO", Codigo = "20146"},
                new BandeiraPadraoConst() { Nome = "CDC CARD", Tipo = "CREDITO", Codigo = "00175"},
                new BandeiraPadraoConst() { Nome = "CDC CARD", Tipo = "DEBITO", Codigo = "20147"},
                new BandeiraPadraoConst() { Nome = "GRAALCARD", Tipo = "CREDITO", Codigo = "00176"},
                new BandeiraPadraoConst() { Nome = "GRAALCARD", Tipo = "DEBITO", Codigo = "20148"},
                new BandeiraPadraoConst() { Nome = "GRANDCARD", Tipo = "CREDITO", Codigo = "00177"},
                new BandeiraPadraoConst() { Nome = "GRANDCARD", Tipo = "DEBITO", Codigo = "20149"},
                new BandeiraPadraoConst() { Nome = "ITACARD", Tipo = "CREDITO", Codigo = "00178"},
                new BandeiraPadraoConst() { Nome = "ITACARD", Tipo = "DEBITO", Codigo = "20150"},
                new BandeiraPadraoConst() { Nome = "REDEMED", Tipo = "CREDITO", Codigo = "00179"},
                new BandeiraPadraoConst() { Nome = "SIANET", Tipo = "CREDITO", Codigo = "00180"},
                new BandeiraPadraoConst() { Nome = "SIANET", Tipo = "DEBITO", Codigo = "20151"},
                new BandeiraPadraoConst() { Nome = "ECXCARD", Tipo = "CREDITO", Codigo = "00181"},
                new BandeiraPadraoConst() { Nome = "ECXCARD COMBUSTIVEL FROTA", Codigo = "10186"},
                new BandeiraPadraoConst() { Nome = "TRUCKPAG COMBUSTIVEL", Codigo = "10187"},
                new BandeiraPadraoConst() { Nome = "DOTZ", Tipo = "CREDITO", Codigo = "00182"},
                new BandeiraPadraoConst() { Nome = "VERDECARD", Tipo = "DEBITO", Codigo = "20152"},
                new BandeiraPadraoConst() { Nome = "VISA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "10188"},
                new BandeiraPadraoConst() { Nome = "MASTER", Tipo = "CREDITO PRIVATE LABEL", Codigo = "10189"},
                new BandeiraPadraoConst() { Nome = "ACICREDI", Tipo = "CREDITO", Codigo = "00183"},
                new BandeiraPadraoConst() { Nome = "AESP CONVENIO", Tipo = "CREDITO", Codigo = "00184"},
                new BandeiraPadraoConst() { Nome = "AGUIA CARD", Tipo = "CREDITO", Codigo = "00185"},
                new BandeiraPadraoConst() { Nome = "ARCOMCREDICARD", Tipo = "CREDITO", Codigo = "00186"},
                new BandeiraPadraoConst() { Nome = "ASSUFOP CARD", Tipo = "CREDITO", Codigo = "00187"},
                new BandeiraPadraoConst() { Nome = "AVANTISYS", Tipo = "CREDITO", Codigo = "00188"},
                new BandeiraPadraoConst() { Nome = "AZUL CARD", Tipo = "VOUCHER", Codigo = "10190"},
                new BandeiraPadraoConst() { Nome = "BANDCARD", Tipo = "CREDITO", Codigo = "00189"},
                new BandeiraPadraoConst() { Nome = "BANDCARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10191"},
                new BandeiraPadraoConst() { Nome = "BANESE", Tipo = "VOUCHER REFEICAO", Codigo = "10192"},
                new BandeiraPadraoConst() { Nome = "BANK", Tipo = "VOUCHER", Codigo = "10193"},
                new BandeiraPadraoConst() { Nome = "BICARTOES", Tipo = "VOUCHER", Codigo = "10194"},
                new BandeiraPadraoConst() { Nome = "BIGCARD", Tipo = "VOUCHER", Codigo = "10195"},
                new BandeiraPadraoConst() { Nome = "BLUEBANK", Tipo = "VOUCHER", Codigo = "10196"},
                new BandeiraPadraoConst() { Nome = "CAMPELOCARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10197"},
                new BandeiraPadraoConst() { Nome = "CAMPELOCARD", Tipo = "CREDITO", Codigo = "00190"},
                new BandeiraPadraoConst() { Nome = "CARTAO CONFIANCA", Tipo = "CREDITO", Codigo = "00191"},
                new BandeiraPadraoConst() { Nome = "CARTAO CONFIANCA", Tipo = "VOUCHER", Codigo = "10198"},
                new BandeiraPadraoConst() { Nome = "CARTAO HORTIFRUTI", Tipo = "CREDITO", Codigo = "00192"},
                new BandeiraPadraoConst() { Nome = "IRANI", Tipo = "CREDITO", Codigo = "00193"},
                new BandeiraPadraoConst() { Nome = "IRANI", Tipo = "VOUCHER", Codigo = "10199"},
                new BandeiraPadraoConst() { Nome = "IRANI", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10200"},
                new BandeiraPadraoConst() { Nome = "CARTAO LEVEMAIS", Tipo = "CREDITO", Codigo = "00194"},
                new BandeiraPadraoConst() { Nome = "CARTAO MONTREAL", Tipo = "CREDITO", Codigo = "00195"},
                new BandeiraPadraoConst() { Nome = "CARTAO NALIN", Tipo = "CREDITO", Codigo = "00196"},
                new BandeiraPadraoConst() { Nome = "CARTOES BRAIZINHO", Tipo = "CREDITO", Codigo = "00197"},
                new BandeiraPadraoConst() { Nome = "CATTANCARD", Tipo = "CREDITO", Codigo = "00198"},
                new BandeiraPadraoConst() { Nome = "CATTANCARD FORTBRASIL", Tipo = "CREDITO", Codigo = "00199"},
                new BandeiraPadraoConst() { Nome = "CLUBE DEMAIS", Tipo = "CREDITO", Codigo = "00200"},
                new BandeiraPadraoConst() { Nome = "CLUBE DEMAIS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10201"},
                new BandeiraPadraoConst() { Nome = "CONDOR", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10202"},
                new BandeiraPadraoConst() { Nome = "COOPECIC CARD", Tipo = "CREDITO", Codigo = "00201"},
                new BandeiraPadraoConst() { Nome = "COOPERATIVO", Tipo = "CREDITO", Codigo = "00202"},
                new BandeiraPadraoConst() { Nome = "CREDIALTO CARD", Tipo = "CREDITO", Codigo = "00203"},
                new BandeiraPadraoConst() { Nome = "CREDINOVA CARD", Tipo = "CREDITO", Codigo = "00204"},
                new BandeiraPadraoConst() { Nome = "CREDIPINHO CARD", Tipo = "CREDITO", Codigo = "00205"},
                new BandeiraPadraoConst() { Nome = "EDIZ", Tipo = "VOUCHER", Codigo = "10203"},
                new BandeiraPadraoConst() { Nome = "ENSCON CARD", Tipo = "VOUCHER", Codigo = "10204"},
                new BandeiraPadraoConst() { Nome = "FINANCIAL CARTOES", Tipo = "CREDITO", Codigo = "00206"},
                new BandeiraPadraoConst() { Nome = "FORMOSA", Tipo = "VOUCHER", Codigo = "10205"},
                new BandeiraPadraoConst() { Nome = "GIRACARD", Tipo = "VOUCHER", Codigo = "10206"},
                new BandeiraPadraoConst() { Nome = "IDEAL SUPERMERCADOS", Tipo = "VOUCHER", Codigo = "10207"},
                new BandeiraPadraoConst() { Nome = "IMPERATRIZ", Tipo = "CREDITO", Codigo = "00207"},
                new BandeiraPadraoConst() { Nome = "IMPERATRIZ", Tipo = "VOUCHER", Codigo = "10208"},
                new BandeiraPadraoConst() { Nome = "LAGOACRED CARD", Tipo = "CREDITO", Codigo = "00208"},
                new BandeiraPadraoConst() { Nome = "MAISFACIL", Tipo = "CREDITO", Codigo = "00209"},
                new BandeiraPadraoConst() { Nome = "NEOCARD", Tipo = "CREDITO", Codigo = "00210"},
                new BandeiraPadraoConst() { Nome = "NEUS", Tipo = "VOUCHER", Codigo = "10209"},
                new BandeiraPadraoConst() { Nome = "NEUS MINAS", Tipo = "VOUCHER", Codigo = "10210"},
                new BandeiraPadraoConst() { Nome = "PAGUEMENOS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10211"},
                new BandeiraPadraoConst() { Nome = "PG CARD", Tipo = "VOUCHER", Codigo = "10212"},
                new BandeiraPadraoConst() { Nome = "PITCARD", Tipo = "CREDITO", Codigo = "00211"},
                new BandeiraPadraoConst() { Nome = "QUEIROZ PREMIUM", Tipo = "CREDITO", Codigo = "00212"},
                new BandeiraPadraoConst() { Nome = "QUEIROZ PREMIUM", Tipo = "VOUCHER", Codigo = "10213"},
                new BandeiraPadraoConst() { Nome = "QUEIROZ PREMIUM", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10214"},
                new BandeiraPadraoConst() { Nome = "REDE CUIDAR", Tipo = "CREDITO", Codigo = "00213"},
                new BandeiraPadraoConst() { Nome = "SAVEGNAGO", Tipo = "CREDITO", Codigo = "00214"},
                new BandeiraPadraoConst() { Nome = "SERTAO CARD", Tipo = "CREDITO", Codigo = "00215"},
                new BandeiraPadraoConst() { Nome = "SERVIR", Tipo = "CREDITO", Codigo = "00216"},
                new BandeiraPadraoConst() { Nome = "SIACARD", Tipo = "CREDITO", Codigo = "00217"},
                new BandeiraPadraoConst() { Nome = "SIM", Tipo = "CREDITO", Codigo = "00218"},
                new BandeiraPadraoConst() { Nome = "SINDCONVENIOS", Tipo = "VOUCHER", Codigo = "10215"},
                new BandeiraPadraoConst() { Nome = "SITECC", Tipo = "CREDITO", Codigo = "00219"},
                new BandeiraPadraoConst() { Nome = "SOLLUS", Tipo = "CREDITO", Codigo = "00220"},
                new BandeiraPadraoConst() { Nome = "SOLLUS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10216"},
                new BandeiraPadraoConst() { Nome = "SOLLUS", Tipo = "VOUCHER REFEICAO", Codigo = "10217"},
                new BandeiraPadraoConst() { Nome = "STILOA CARD", Tipo = "CREDITO", Codigo = "00221"},
                new BandeiraPadraoConst() { Nome = "SUPERCRED", Tipo = "CREDITO", Codigo = "00222"},
                new BandeiraPadraoConst() { Nome = "TIPCARD", Tipo = "CREDITO", Codigo = "00223"},
                new BandeiraPadraoConst() { Nome = "TORRA TORRA", Tipo = "CREDITO", Codigo = "00224"},
                new BandeiraPadraoConst() { Nome = "UAICARD", Tipo = "CREDITO", Codigo = "00225"},
                new BandeiraPadraoConst() { Nome = "SUPERCRED", Tipo = "VOUCHER", Codigo = "10218"},
                new BandeiraPadraoConst() { Nome = "VALEMAIS", Tipo = "VOUCHER", Codigo = "10219"},
                new BandeiraPadraoConst() { Nome = "VALEMAIS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10220"},
                new BandeiraPadraoConst() { Nome = "VALLE REAL", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10221"},
                new BandeiraPadraoConst() { Nome = "VEGAS", Tipo = "VOUCHER", Codigo = "10222"},
                new BandeiraPadraoConst() { Nome = "VIPCARD", Tipo = "CREDITO", Codigo = "00226"},
                new BandeiraPadraoConst() { Nome = "ZEMA", Tipo = "CREDITO", Codigo = "00227"},
                new BandeiraPadraoConst() { Nome = "PAGUEMENOS", Tipo = "VOUCHER BENEFICIO", Codigo = "10223"},
                new BandeiraPadraoConst() { Nome = "PARACATU CARD", Tipo = "VOUCHER BENEFICIO", Codigo = "10224"},
                new BandeiraPadraoConst() { Nome = "SERVIR", Tipo = "VOUCHER BENEFICIO", Codigo = "10225"},
                new BandeiraPadraoConst() { Nome = "SERTAO CARD", Tipo = "VOUCHER BENEFICIO", Codigo = "10226"},
                new BandeiraPadraoConst() { Nome = "SINTRAM", Tipo = "VOUCHER BENEFICIO", Codigo = "10227"},
                new BandeiraPadraoConst() { Nome = "VALEMAIS", Tipo = "VOUCHER BENEFICIO", Codigo = "10228"},
                new BandeiraPadraoConst() { Nome = "VALLE REAL", Tipo = "VOUCHER BENEFICIO", Codigo = "10229"},
                new BandeiraPadraoConst() { Nome = "SFORZA", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10230"},
                new BandeiraPadraoConst() { Nome = "SFORZA", Tipo = "VOUCHER REFEICAO", Codigo = "10231"},
                new BandeiraPadraoConst() { Nome = "SISCRED", Tipo = "CREDITO", Codigo = "00228"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "VOUCHER ALIMENTAÇÃO", Codigo = "10237"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "VOUCHER REFEIÇÃO", Codigo = "10238"},
                new BandeiraPadraoConst() { Nome = "BRADESCARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00231"},
                new BandeiraPadraoConst() { Nome = "BRADESCARD ELO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00232"},
                new BandeiraPadraoConst() { Nome = "BRADESCARD VISA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00233"},
                new BandeiraPadraoConst() { Nome = "BRADESCARD MASTERCARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00234"},
                new BandeiraPadraoConst() { Nome = "VALEPRES SYSDATA", Tipo = "GIFT", Codigo = "10239"},
                new BandeiraPadraoConst() { Nome = "VALEPRES PEELA", Tipo = "GIFT", Codigo = "10240"},
                new BandeiraPadraoConst() { Nome = "GOLDENFARMA", Tipo = "CREDITO", Codigo = "00235"},
                new BandeiraPadraoConst() { Nome = "MAISFACIL", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00237"},
                new BandeiraPadraoConst() { Nome = "BLACKHAWK GIFT", Tipo = "GIFT", Codigo = "10252"},
                new BandeiraPadraoConst() { Nome = "BLACKHAWK PRÉ-PAGO", Tipo = "DEBITO PRIVATE LABEL", Codigo = "20155"},
                new BandeiraPadraoConst() { Nome = "PIC PAY", Tipo = "CARTEIRA DIGITAL", Codigo = "600012"},
                new BandeiraPadraoConst() { Nome = "VEE", Tipo = "CARTEIRA DIGITAL", Codigo = "260005"},
                new BandeiraPadraoConst() { Nome = "MERCADO PAGO", Tipo = "CARTEIRA DIGITAL", Codigo = "290006"},
                new BandeiraPadraoConst() { Nome = "ITI ITAU", Tipo = "CARTEIRA DIGITAL", Codigo = "380009"},                
                new BandeiraPadraoConst() { Nome = "PIX", Tipo = "CARTEIRA DIGITAL", Codigo = "60110024"}
            };
        }
        public static BandeiraPadraoConst RetornarBandeiraPadrao(int _codigo)
        {
            return RetornarLista().Find(p => p.CodigoInt == _codigo);
        }
    }
}
