using System;
using System.Collections.Generic;

namespace Lib.CliSitef.ConstantValues
{
    public class BandeiraPadraoConst
    {
        public string Codigo { get; set; }
        public string Nome { get; set; }
        public string Tipo { get; set; }

        public int CodigoInt
        {
            get
            {
                return string.IsNullOrWhiteSpace(Codigo) ? 0 : Convert.ToInt32(Codigo);
            }
        }

        public string NomeTipo
        {
            get
            {
                return string.IsNullOrWhiteSpace(Nome) ? "" : Nome + " - " + Tipo;
            }
        }

        public string NomeTipoCodigo
        {
            get
            {
                return string.IsNullOrWhiteSpace(Nome) ? "" : Nome + "|" + Tipo + "|" + Codigo;
            }
        }
    }

    public class BandeiraPadrao
    {
        public static List<BandeiraPadraoConst> RetornarLista()
        {
            return new List<BandeiraPadraoConst>()
            {
                new BandeiraPadraoConst() { Nome = "OUTRO, NÃO DEFINIDO", Tipo = "", Codigo = "00000"},
                new BandeiraPadraoConst() { Nome = "VISA", Tipo = "CREDITO", Codigo = "00001"},
                new BandeiraPadraoConst() { Nome = "VISA", Tipo = "DEBITO", Codigo = "20002"},
                new BandeiraPadraoConst() { Nome = "VISA", Tipo = "VOUCHER", Codigo = "10002"},
                new BandeiraPadraoConst() { Nome = "VISA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "10188"},
                new BandeiraPadraoConst() { Nome = "MASTER", Tipo = "CREDITO", Codigo = "00002"},
                new BandeiraPadraoConst() { Nome = "MASTER", Tipo = "DEBITO", Codigo = "20001"},
                new BandeiraPadraoConst() { Nome = "MASTER", Tipo = "CREDITO PRIVATE LABEL", Codigo = "10189"},
                new BandeiraPadraoConst() { Nome = "MASTER", Tipo = "VOUCHER", Codigo = "10266"},
                new BandeiraPadraoConst() { Nome = "MASTER", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10230"},
                new BandeiraPadraoConst() { Nome = "MASTER", Tipo = "VOUCHER REFEICAO", Codigo = "10231"},
                new BandeiraPadraoConst() { Nome = "AMEX", Tipo = "CREDITO", Codigo = "00004"},
                new BandeiraPadraoConst() { Nome = "AMEX", Tipo = "VOUCHER", Codigo = "10267"},
                new BandeiraPadraoConst() { Nome = "FINIVEST", Tipo = "CREDITO", Codigo = "00010"},
                new BandeiraPadraoConst() { Nome = "HIPER", Tipo = "CREDITO", Codigo = "00012"},
                new BandeiraPadraoConst() { Nome = "HIPER", Tipo = "DEBITO", Codigo = "20037"},
                new BandeiraPadraoConst() { Nome = "DINERS", Tipo = "CREDITO", Codigo = "00003"},
                new BandeiraPadraoConst() { Nome = "DINERS", Tipo = "VOUCHER", Codigo = "10014"},
                new BandeiraPadraoConst() { Nome = "ITAU", Tipo = "CARTEIRA DIGITAL", Codigo = "10268"},
                new BandeiraPadraoConst() { Nome = "JCB", Tipo = "CREDITO", Codigo = "00011"},
                new BandeiraPadraoConst() { Nome = "AURA", Tipo = "CREDITO", Codigo = "00013"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "CREDITO", Codigo = "10003"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "VOUCHER REFEICAO", Codigo = "10028"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10029"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "GIFT", Codigo = "10030"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "VOUCHER", Codigo = "10031"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "VOUCHER CULTURA", Codigo = "10032"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "COMBUSTIVEL", Codigo = "10033"},
                new BandeiraPadraoConst() { Nome = "SODEXO", Tipo = "VOUCHER BENEFICIO", Codigo = "10269"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "CREDITO", Codigo = "00130"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "DEBITO", Codigo = "20131"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "VOUCHER REFEICAO", Codigo = "10133"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10134"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "VOUCHER", Codigo = "10132"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "COMBUSTIVEL", Codigo = "10135"},
                new BandeiraPadraoConst() { Nome = "SOROCRED", Tipo = "CREDITO", Codigo = "00015"},
                new BandeiraPadraoConst() { Nome = "SOROCRED", Tipo = "VOUCHER", Codigo = "10037"},
                new BandeiraPadraoConst() { Nome = "SOROCRED", Tipo = "DEBITO", Codigo = "20071"},
                new BandeiraPadraoConst() { Nome = "SOROCRED", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10355"},
                new BandeiraPadraoConst() { Nome = "SOROCRED", Tipo = "VOUCHER REFEICAO", Codigo = "10356"},
                new BandeiraPadraoConst() { Nome = "SOROCRED", Tipo = "COMBUSTIVEL", Codigo = "10370"},
                new BandeiraPadraoConst() { Nome = "CARDBAN", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00271"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "CREDITO", Codigo = "00033"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "DEBITO", Codigo = "20034"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "VOUCHER REFEICAO", Codigo = "10165"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10164"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "VOUCHER CULTURA", Codigo = "10178"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "GIFT", Codigo = "10168"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "VOUCHER", Codigo = "10162"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "COMBUSTIVEL FROTA", Codigo = "10163"},
                new BandeiraPadraoConst() { Nome = "POLICARD", Tipo = "COMBUSTIVEL", Codigo = "10179"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "VOUCHER", Codigo = "10001"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "VOUCHER REFEICAO", Codigo = "10024"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10025"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "VOUCHER CULTURA", Codigo = "10027"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "COMBUSTIVEL", Codigo = "10054"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "CREDITO", Codigo = "00072"},
                new BandeiraPadraoConst() { Nome = "TICKET", Tipo = "DEBITO", Codigo = "20076"},
                new BandeiraPadraoConst() { Nome = "ELO", Tipo = "CREDITO", Codigo = "00031"},
                new BandeiraPadraoConst() { Nome = "ELO", Tipo = "DEBITO", Codigo = "20032"},
                new BandeiraPadraoConst() { Nome = "ELO", Tipo = "COMBUSTIVEL", Codigo = "10082"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "DEBITO", Codigo = "20003"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "VOUCHER", Codigo = "10012"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "CREDITO", Codigo = "00030"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "DEBITO PRIVATE LABEL", Codigo = "20189"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "VOUCHER REFEICAO", Codigo = "10270"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10271"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "VOUCHER CULTURA", Codigo = "10272"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "GIFT", Codigo = "10357"},
                new BandeiraPadraoConst() { Nome = "CABAL", Tipo = "COMBUSTIVEL", Codigo = "10358"},
                new BandeiraPadraoConst() { Nome = "VERDECARD", Tipo = "CREDITO", Codigo = "00086"},
                new BandeiraPadraoConst() { Nome = "VERDECARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00086"},
                new BandeiraPadraoConst() { Nome = "VERDECARD", Tipo = "DEBITO", Codigo = "20152"},
                new BandeiraPadraoConst() { Nome = "UNIK", Tipo = "CREDITO", Codigo = "00272"},
                new BandeiraPadraoConst() { Nome = "VEROCHEQUE", Tipo = "CREDITO", Codigo = "00269"},
                new BandeiraPadraoConst() { Nome = "VEROCHEQUE", Tipo = "VOUCHER", Codigo = "10008"},
                new BandeiraPadraoConst() { Nome = "VEROCHEQUE", Tipo = "VOUCHER CULTURA", Codigo = "10090"},
                new BandeiraPadraoConst() { Nome = "VEROCHEQUE", Tipo = "COMBUSTIVEL", Codigo = "10265"},
                new BandeiraPadraoConst() { Nome = "VEROCHEQUE", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10176"},
                new BandeiraPadraoConst() { Nome = "VEROCHEQUE", Tipo = "VOUCHER REFEICAO", Codigo = "10177"},
                new BandeiraPadraoConst() { Nome = "BONUS CBA", Tipo = "CREDITO", Codigo = "00273"},
                new BandeiraPadraoConst() { Nome = "BONUS CBA", Tipo = "COMBUSTIVEL", Codigo = "10273"},
                new BandeiraPadraoConst() { Nome = "BONUS CBA", Tipo = "VOUCHER", Codigo = "10274"},
                new BandeiraPadraoConst() { Nome = "MAIS", Tipo = "CREDITO", Codigo = "00057"},
                new BandeiraPadraoConst() { Nome = "MAIS", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00408"},
                new BandeiraPadraoConst() { Nome = "SAPORE", Tipo = "VOUCHER", Codigo = "10009"},
                new BandeiraPadraoConst() { Nome = "ESPLANA", Tipo = "CREDITO", Codigo = "00274"},
                new BandeiraPadraoConst() { Nome = "AGIPLAN", Tipo = "CREDITO", Codigo = "00275"},
                new BandeiraPadraoConst() { Nome = "AGIPLAN", Tipo = "DEBITO", Codigo = "20250"},
                new BandeiraPadraoConst() { Nome = "BANESCARD", Tipo = "CREDITO", Codigo = "00035"},
                new BandeiraPadraoConst() { Nome = "BANESCARD", Tipo = "DEBITO", Codigo = "20036"},
                new BandeiraPadraoConst() { Nome = "FORTBRASIL", Tipo = "CREDITO", Codigo = "00137"},
                new BandeiraPadraoConst() { Nome = "FORTBRASIL", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00276"},
                new BandeiraPadraoConst() { Nome = "TIPCARD", Tipo = "COMBUSTIVEL", Codigo = "10275"},
                new BandeiraPadraoConst() { Nome = "TIPCARD", Tipo = "CREDITO", Codigo = "00223"},
                new BandeiraPadraoConst() { Nome = "ABC", Tipo = "CREDITO", Codigo = "00277"},
                new BandeiraPadraoConst() { Nome = "AVISTA", Tipo = "CREDITO", Codigo = "00045"},
                new BandeiraPadraoConst() { Nome = "AVISTA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00278"},
                new BandeiraPadraoConst() { Nome = "BIQ", Tipo = "VOUCHER REFEICAO", Codigo = "10276"},
                new BandeiraPadraoConst() { Nome = "BIQ", Tipo = "VOUCHER", Codigo = "10144"},
                new BandeiraPadraoConst() { Nome = "BNBCLUBE", Tipo = "VOUCHER", Codigo = "10010"},
                new BandeiraPadraoConst() { Nome = "BNBCLUBE", Tipo = "VOUCHER REFEICAO", Codigo = "10277"},
                new BandeiraPadraoConst() { Nome = "BNBCLUBE", Tipo = "CREDITO", Codigo = "00173"},
                new BandeiraPadraoConst() { Nome = "BNBCLUBE", Tipo = "DEBITO", Codigo = "20145"},
                new BandeiraPadraoConst() { Nome = "CALCARD", Tipo = "CREDITO", Codigo = "00090"},
                new BandeiraPadraoConst() { Nome = "CREDISHOP", Tipo = "CREDITO", Codigo = "00071"},
                new BandeiraPadraoConst() { Nome = "MINASCRED", Tipo = "CREDITO", Codigo = "00279"},
                new BandeiraPadraoConst() { Nome = "MINASCRED", Tipo = "DEBITO", Codigo = "20190"},
                new BandeiraPadraoConst() { Nome = "NUTRICASH", Tipo = "VOUCHER", Codigo = "10004"},
                new BandeiraPadraoConst() { Nome = "NUTRICASH", Tipo = "COMBUSTIVEL", Codigo = "10278"},
                new BandeiraPadraoConst() { Nome = "NUTRICASH", Tipo = "VOUCHER CULTURA", Codigo = "10053"},
                new BandeiraPadraoConst() { Nome = "NUTRICASH", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10359"},
                new BandeiraPadraoConst() { Nome = "NUTRICASH", Tipo = "VOUCHER REFEICAO", Codigo = "10360"},
                new BandeiraPadraoConst() { Nome = "NUTRICASH", Tipo = "VOUCHER BENEFICIO", Codigo = "10361"},
                new BandeiraPadraoConst() { Nome = "OBOECARD", Tipo = "CREDITO", Codigo = "00280"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER", Codigo = "10006"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER CULTURA", Codigo = "10051"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "COMBUSTIVEL", Codigo = "10074"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10072"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER REFEICAO", Codigo = "10073"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER FARMACIA", Codigo = "10075"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "VOUCHER BENEFICIO", Codigo = "10071"},
                new BandeiraPadraoConst() { Nome = "PLANVALE", Tipo = "DEBITO", Codigo = "20181"},
                new BandeiraPadraoConst() { Nome = "REDECOMPRAS", Tipo = "CREDITO", Codigo = "00281"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "VOUCHER", Codigo = "10005"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "DEBITO", Codigo = "20191"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "COMBUSTIVEL", Codigo = "10279"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10173"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "VOUCHER REFEICAO", Codigo = "10174"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "VOUCHER CULTURA", Codigo = "10175"},
                new BandeiraPadraoConst() { Nome = "GREENCARD", Tipo = "CREDITO", Codigo = "00473"},
                new BandeiraPadraoConst() { Nome = "CREDIALIMENT", Tipo = "VOUCHER", Codigo = "10280"},
                new BandeiraPadraoConst() { Nome = "TRICARD", Tipo = "CREDITO", Codigo = "00093"},
                new BandeiraPadraoConst() { Nome = "TRICARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00094"},
                new BandeiraPadraoConst() { Nome = "BANQUET", Tipo = "VOUCHER", Codigo = "10007"},
                new BandeiraPadraoConst() { Nome = "BANRISUL", Tipo = "CREDITO", Codigo = "00084"},
                new BandeiraPadraoConst() { Nome = "BANRISUL", Tipo = "DEBITO", Codigo = "20085"},
                new BandeiraPadraoConst() { Nome = "REFEISUL", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10089"},
                new BandeiraPadraoConst() { Nome = "REFEISUL", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00087"},
                new BandeiraPadraoConst() { Nome = "REFEISUL", Tipo = "COMBUSTIVEL", Codigo = "10088"},
                new BandeiraPadraoConst() { Nome = "REFEISUL", Tipo = "VOUCHER CULTURA", Codigo = "10052"},
                new BandeiraPadraoConst() { Nome = "REFEISUL", Tipo = "VOUCHER", Codigo = "10281"},
                new BandeiraPadraoConst() { Nome = "SICREDI", Tipo = "CREDITO", Codigo = "00041"},
                new BandeiraPadraoConst() { Nome = "SICREDI", Tipo = "DEBITO", Codigo = "20042"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "CREDITO", Codigo = "00043"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "VOUCHER", Codigo = "10044"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "VOUCHER CULTURA", Codigo = "10056"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "DEBITO", Codigo = "20132"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10137"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "VOUCHER REFEICAO", Codigo = "10138"},
                new BandeiraPadraoConst() { Nome = "COOPERCRED", Tipo = "GIFT", Codigo = "10172"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "VOUCHER", Codigo = "10011"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "DEBITO", Codigo = "20192"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "VOUCHER CULTURA", Codigo = "10055"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "NENHUM", Codigo = "10282"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10237"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "VOUCHER REFEICAO", Codigo = "10238"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "CREDITO", Codigo = "00282"},
                new BandeiraPadraoConst() { Nome = "VALECARD", Tipo = "COMBUSTIVEL", Codigo = "10283"},
                new BandeiraPadraoConst() { Nome = "VALEFACIL", Tipo = "VOUCHER", Codigo = "10046"},
                new BandeiraPadraoConst() { Nome = "VALEMULTI", Tipo = "VOUCHER", Codigo = "10039"},
                new BandeiraPadraoConst() { Nome = "VALEFROTA", Tipo = "VOUCHER", Codigo = "10040"},
                new BandeiraPadraoConst() { Nome = "VALEFROTA", Tipo = "COMBUSTIVEL", Codigo = "10284"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "VOUCHER REFEICAO", Codigo = "10047"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10048"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "COMBUSTIVEL", Codigo = "10049"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "VOUCHER CULTURA", Codigo = "10050"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "VOUCHER BENEFICIO", Codigo = "10070"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "VOUCHER", Codigo = "10083"},
                new BandeiraPadraoConst() { Nome = "VR", Tipo = "GIFT", Codigo = "10285"},
                new BandeiraPadraoConst() { Nome = "CREDZ", Tipo = "CREDITO", Codigo = "00070"},
                new BandeiraPadraoConst() { Nome = "GPA", Tipo = "CREDITO", Codigo = "00283"},
                new BandeiraPadraoConst() { Nome = "GPA", Tipo = "VOUCHER", Codigo = "10286"},
                new BandeiraPadraoConst() { Nome = "SIDECARD", Tipo = "CREDITO", Codigo = "00006"},
                new BandeiraPadraoConst() { Nome = "REDESHOP", Tipo = "CREDITO", Codigo = "00008"},
                new BandeiraPadraoConst() { Nome = "LOSANGO", Tipo = "CREDITO", Codigo = "00014"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "CREDITO", Codigo = "00284"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "VOUCHER REFEICAO", Codigo = "10021"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10022"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "VOUCHER CULTURA", Codigo = "10023"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "COMBUSTIVEL", Codigo = "10381"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "COMBUSTIVEL FROTA", Codigo = "10082"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "VOUCHER", Codigo = "10019"},
                new BandeiraPadraoConst() { Nome = "ALELO", Tipo = "VOUCHER BENEFICIO", Codigo = "10242"},
                new BandeiraPadraoConst() { Nome = "BANPARA", Tipo = "VOUCHER", Codigo = "10287"},
                new BandeiraPadraoConst() { Nome = "BANPARA", Tipo = "CREDITO", Codigo = "00058"},
                new BandeiraPadraoConst() { Nome = "BANPARA", Tipo = "DEBITO", Codigo = "20059"},
                new BandeiraPadraoConst() { Nome = "AMAZONCARD", Tipo = "VOUCHER", Codigo = "10288"},
                new BandeiraPadraoConst() { Nome = "AMAZONCARD", Tipo = "CREDITO", Codigo = "00060"},
                new BandeiraPadraoConst() { Nome = "YAMADA", Tipo = "VOUCHER", Codigo = "10289"},
                new BandeiraPadraoConst() { Nome = "YAMADA", Tipo = "CREDITO", Codigo = "00061"},
                new BandeiraPadraoConst() { Nome = "GOIASCARD", Tipo = "VOUCHER", Codigo = "10290"},
                new BandeiraPadraoConst() { Nome = "GOIASCARD", Tipo = "CREDITO", Codigo = "00062"},
                new BandeiraPadraoConst() { Nome = "CREDPAR", Tipo = "VOUCHER", Codigo = "10291"},
                new BandeiraPadraoConst() { Nome = "CREDPAR", Tipo = "CREDITO", Codigo = "00063"},
                new BandeiraPadraoConst() { Nome = "BOTICARIO", Tipo = "CREDITO", Codigo = "00064"},
                new BandeiraPadraoConst() { Nome = "ASCARD", Tipo = "CREDITO", Codigo = "00065"},
                new BandeiraPadraoConst() { Nome = "JETPAR", Tipo = "CREDITO", Codigo = "00066"},
                new BandeiraPadraoConst() { Nome = "MAXXCARD", Tipo = "CREDITO", Codigo = "00067"},
                new BandeiraPadraoConst() { Nome = "MAXXCARD", Tipo = "VOUCHER", Codigo = "10292"},
                new BandeiraPadraoConst() { Nome = "MAXXCARD", Tipo = "DEBITO", Codigo = "20193"},
                new BandeiraPadraoConst() { Nome = "MAXXCARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10362"},
                new BandeiraPadraoConst() { Nome = "MAXXCARD", Tipo = "VOUCHER REFEICAO", Codigo = "10363"},
                new BandeiraPadraoConst() { Nome = "MAXXCARD", Tipo = "COMBUSTIVEL", Codigo = "10364"},
                new BandeiraPadraoConst() { Nome = "MAXXCARD", Tipo = "VOUCHER CULTURA", Codigo = "10365"},
                new BandeiraPadraoConst() { Nome = "GARANTIDO", Tipo = "CREDITO", Codigo = "00068"},
                new BandeiraPadraoConst() { Nome = "AMAZONPRIME", Tipo = "CREDITO", Codigo = "00069"},
                new BandeiraPadraoConst() { Nome = "CETELEM", Tipo = "CREDITO", Codigo = "00038"},
                new BandeiraPadraoConst() { Nome = "PAO DE ACUCAR", Tipo = "CREDITO", Codigo = "00009"},
                new BandeiraPadraoConst() { Nome = "PRIVATE LABEL GENERICO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00007"},
                new BandeiraPadraoConst() { Nome = "BANESE", Tipo = "CREDITO", Codigo = "00091"},
                new BandeiraPadraoConst() { Nome = "BANESE", Tipo = "DEBITO", Codigo = "20092"},
                new BandeiraPadraoConst() { Nome = "BANESE", Tipo = "VOUCHER", Codigo = "10293"},
                new BandeiraPadraoConst() { Nome = "BANESE", Tipo = "VOUCHER REFEICAO", Codigo = "10192"},
                new BandeiraPadraoConst() { Nome = "CARDCO", Tipo = "CREDITO", Codigo = "00285"},
                new BandeiraPadraoConst() { Nome = "CCS", Tipo = "CREDITO", Codigo = "00286"},
                new BandeiraPadraoConst() { Nome = "CENTRAL CARD", Tipo = "CREDITO", Codigo = "00287"},
                new BandeiraPadraoConst() { Nome = "CHECK CHECK", Tipo = "CREDITO", Codigo = "00288"},
                new BandeiraPadraoConst() { Nome = "COMPRO CARD", Tipo = "CREDITO", Codigo = "00289"},
                new BandeiraPadraoConst() { Nome = "CONV CARD", Tipo = "CREDITO", Codigo = "00290"},
                new BandeiraPadraoConst() { Nome = "DACASA", Tipo = "CREDITO", Codigo = "00291"},
                new BandeiraPadraoConst() { Nome = "EDMCARD", Tipo = "CREDITO", Codigo = "00292"},
                new BandeiraPadraoConst() { Nome = "EXPANSIVA", Tipo = "CREDITO", Codigo = "00293"},
                new BandeiraPadraoConst() { Nome = "GIVEX", Tipo = "DEBITO", Codigo = "20194"},
                new BandeiraPadraoConst() { Nome = "MAXICRED", Tipo = "CREDITO", Codigo = "00294"},
                new BandeiraPadraoConst() { Nome = "MULTICHEQUE", Tipo = "CREDITO", Codigo = "00295"},
                new BandeiraPadraoConst() { Nome = "PROTEGE", Tipo = "CREDITO", Codigo = "00296"},
                new BandeiraPadraoConst() { Nome = "SEICON", Tipo = "CREDITO", Codigo = "00297"},
                new BandeiraPadraoConst() { Nome = "SIGACRED", Tipo = "CREDITO", Codigo = "00298"},
                new BandeiraPadraoConst() { Nome = "SUPERCARD", Tipo = "CREDITO", Codigo = "00299"},
                new BandeiraPadraoConst() { Nome = "TCREDIT", Tipo = "CREDITO", Codigo = "00300"},
                new BandeiraPadraoConst() { Nome = "TOTAL", Tipo = "CREDITO", Codigo = "00301"},
                new BandeiraPadraoConst() { Nome = "HOTCARD", Tipo = "CREDITO", Codigo = "00302"},
                new BandeiraPadraoConst() { Nome = "FORMOSA", Tipo = "CREDITO", Codigo = "00303"},
                new BandeiraPadraoConst() { Nome = "FORMOSA", Tipo = "VOUCHER", Codigo = "10205"},
                new BandeiraPadraoConst() { Nome = "VALECON", Tipo = "CREDITO", Codigo = "00304"},
                new BandeiraPadraoConst() { Nome = "FORTCARD", Tipo = "CREDITO", Codigo = "00148"},
                new BandeiraPadraoConst() { Nome = "BANCO GE", Tipo = "CREDITO", Codigo = "00305"},
                new BandeiraPadraoConst() { Nome = "VOLUS", Tipo = "CREDITO", Codigo = "00144"},
                new BandeiraPadraoConst() { Nome = "VOLUS", Tipo = "COMBUSTIVEL", Codigo = "10263"},
                new BandeiraPadraoConst() { Nome = "VOLUS", Tipo = "VOUCHER", Codigo = "10146"},
                new BandeiraPadraoConst() { Nome = "VOLUS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10366"},
                new BandeiraPadraoConst() { Nome = "VOLUS", Tipo = "VOUCHER REFEICAO", Codigo = "10367"},
                new BandeiraPadraoConst() { Nome = "VOLUS", Tipo = "DEBITO", Codigo = "20251"},
                new BandeiraPadraoConst() { Nome = "DTRANSFER", Tipo = "CREDITO", Codigo = "00306"},
                new BandeiraPadraoConst() { Nome = "EXPANDCARD", Tipo = "CREDITO", Codigo = "00307"},
                new BandeiraPadraoConst() { Nome = "SOFTCARD", Tipo = "CREDITO", Codigo = "00308"},
                new BandeiraPadraoConst() { Nome = "COCIPA", Tipo = "CREDITO", Codigo = "00309"},
                new BandeiraPadraoConst() { Nome = "SIMCRED", Tipo = "CREDITO", Codigo = "00310"},
                new BandeiraPadraoConst() { Nome = "ALGORIX", Tipo = "CREDITO", Codigo = "00161"},
                new BandeiraPadraoConst() { Nome = "ALGORIX", Tipo = "DEBITO", Codigo = "20139"},
                new BandeiraPadraoConst() { Nome = "DDTOTAL", Tipo = "CREDITO", Codigo = "00311"},
                new BandeiraPadraoConst() { Nome = "DDTOTAL", Tipo = "DEBITO", Codigo = "20195"},
                new BandeiraPadraoConst() { Nome = "ELETROZEMA", Tipo = "CREDITO", Codigo = "00312"},
                new BandeiraPadraoConst() { Nome = "FACILCARD", Tipo = "CREDITO", Codigo = "00160"},
                new BandeiraPadraoConst() { Nome = "FINAMAX", Tipo = "CREDITO", Codigo = "00313"},
                new BandeiraPadraoConst() { Nome = "ICARDS", Tipo = "CREDITO", Codigo = "00132"},
                new BandeiraPadraoConst() { Nome = "SCCARD", Tipo = "CREDITO", Codigo = "00314"},
                new BandeiraPadraoConst() { Nome = "SCCARD", Tipo = "DEBITO", Codigo = "20196"},
                new BandeiraPadraoConst() { Nome = "VEGASCARD", Tipo = "CREDITO", Codigo = "00141"},
                new BandeiraPadraoConst() { Nome = "VEGASCARD", Tipo = "DEBITO", Codigo = "20133"},
                new BandeiraPadraoConst() { Nome = "VEGASCARD", Tipo = "VOUCHER", Codigo = "10159"},
                new BandeiraPadraoConst() { Nome = "VEGASCARD", Tipo = "COMBUSTIVEL FROTA", Codigo = "10253"},
                new BandeiraPadraoConst() { Nome = "VALESHOP", Tipo = "CREDITO", Codigo = "00315"},
                new BandeiraPadraoConst() { Nome = "VALESHOP", Tipo = "COMBUSTIVEL", Codigo = "10180"},
                new BandeiraPadraoConst() { Nome = "VALESHOP", Tipo = "DEBITO", Codigo = "20197"},
                new BandeiraPadraoConst() { Nome = "VALESHOP", Tipo = "VOUCHER", Codigo = "10158"},
                new BandeiraPadraoConst() { Nome = "GCARD", Tipo = "CREDITO", Codigo = "00316"},
                new BandeiraPadraoConst() { Nome = "GCARD", Tipo = "COMBUSTIVEL", Codigo = "10294"},
                new BandeiraPadraoConst() { Nome = "TOPCARD", Tipo = "CREDITO", Codigo = "00317"},
                new BandeiraPadraoConst() { Nome = "TOPCARD", Tipo = "COMBUSTIVEL", Codigo = "10295"},
                new BandeiraPadraoConst() { Nome = "SOMARCARD", Tipo = "CREDITO", Codigo = "00318"},
                new BandeiraPadraoConst() { Nome = "CONDOR", Tipo = "CREDITO", Codigo = "00319"},
                new BandeiraPadraoConst() { Nome = "CONDOR", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10202"},
                new BandeiraPadraoConst() { Nome = "GAX", Tipo = "COMBUSTIVEL", Codigo = "10296"},
                new BandeiraPadraoConst() { Nome = "USECRED", Tipo = "CREDITO", Codigo = "00320"},
                new BandeiraPadraoConst() { Nome = "USECRED", Tipo = "VOUCHER", Codigo = "10157"},
                new BandeiraPadraoConst() { Nome = "SISCRED", Tipo = "CREDITO", Codigo = "00228"},
                new BandeiraPadraoConst() { Nome = "DMCARD", Tipo = "CREDITO", Codigo = "00321"},
                new BandeiraPadraoConst() { Nome = "BANCRED", Tipo = "CREDITO", Codigo = "00322"},
                new BandeiraPadraoConst() { Nome = "BANCRED", Tipo = "DEBITO", Codigo = "20198"},
                new BandeiraPadraoConst() { Nome = "BRAZILIANCARD", Tipo = "CREDITO", Codigo = "00323"},
                new BandeiraPadraoConst() { Nome = "BRAZILIANCARD", Tipo = "DEBITO", Codigo = "20199"},
                new BandeiraPadraoConst() { Nome = "FIDELIZE", Tipo = "CREDITO", Codigo = "00324"},
                new BandeiraPadraoConst() { Nome = "WORKERCARD", Tipo = "CREDITO", Codigo = "00325"},
                new BandeiraPadraoConst() { Nome = "WORKERCARD", Tipo = "DEBITO", Codigo = "20200"},
                new BandeiraPadraoConst() { Nome = "ACCCARD", Tipo = "CREDITO", Codigo = "00326"},
                new BandeiraPadraoConst() { Nome = "CARTAO EVANGELICO", Tipo = "CREDITO", Codigo = "00327"},
                new BandeiraPadraoConst() { Nome = "ACCREDITO", Tipo = "CREDITO", Codigo = "00172"},
                new BandeiraPadraoConst() { Nome = "ACCREDITO", Tipo = "DEBITO", Codigo = "20144"},
                new BandeiraPadraoConst() { Nome = "ACCREDITO", Tipo = "VOUCHER", Codigo = "10185"},
                new BandeiraPadraoConst() { Nome = "BANESTIK", Tipo = "DEBITO", Codigo = "20201"},
                new BandeiraPadraoConst() { Nome = "BARIGUI", Tipo = "CREDITO", Codigo = "00328"},
                new BandeiraPadraoConst() { Nome = "GAZINCRED", Tipo = "CREDITO", Codigo = "00329"},
                new BandeiraPadraoConst() { Nome = "GAZINCRED", Tipo = "DEBITO", Codigo = "20202"},
                new BandeiraPadraoConst() { Nome = "MARKETPAY", Tipo = "CREDITO", Codigo = "00169"},
                new BandeiraPadraoConst() { Nome = "MARKETPAY", Tipo = "DEBITO", Codigo = "20203"},
                new BandeiraPadraoConst() { Nome = "SIANET", Tipo = "CREDITO", Codigo = "00180"},
                new BandeiraPadraoConst() { Nome = "SIANET", Tipo = "DEBITO", Codigo = "20151"},
                new BandeiraPadraoConst() { Nome = "VALIDATA", Tipo = "CREDITO", Codigo = "00330"},
                new BandeiraPadraoConst() { Nome = "VALIDATA", Tipo = "DEBITO", Codigo = "20204"},
                new BandeiraPadraoConst() { Nome = "UPSIGHT", Tipo = "CREDITO", Codigo = "00331"},
                new BandeiraPadraoConst() { Nome = "UPSIGHT", Tipo = "DEBITO", Codigo = "20205"},
                new BandeiraPadraoConst() { Nome = "UPSIGHT", Tipo = "GIFT", Codigo = "10297"},
                new BandeiraPadraoConst() { Nome = "PORTALCARD", Tipo = "CREDITO", Codigo = "00165"},
                new BandeiraPadraoConst() { Nome = "PORTALCARD", Tipo = "DEBITO", Codigo = "20140"},
                new BandeiraPadraoConst() { Nome = "PORTALCARD", Tipo = "COMBUSTIVEL", Codigo = "10181"},
                new BandeiraPadraoConst() { Nome = "SOFTNEX", Tipo = "CREDITO", Codigo = "00127"},
                new BandeiraPadraoConst() { Nome = "SOFTNEX", Tipo = "VOUCHER", Codigo = "10129"},
                new BandeiraPadraoConst() { Nome = "SOFTNEX", Tipo = "DEBITO", Codigo = "20128"},
                new BandeiraPadraoConst() { Nome = "PEELA", Tipo = "CREDITO", Codigo = "00078"},
                new BandeiraPadraoConst() { Nome = "PEELA", Tipo = "GIFT", Codigo = "10076"},
                new BandeiraPadraoConst() { Nome = "RESOMAQ", Tipo = "CREDITO", Codigo = "00332"},
                new BandeiraPadraoConst() { Nome = "RESOMAQ", Tipo = "DEBITO", Codigo = "20206"},
                new BandeiraPadraoConst() { Nome = "ORGCARD", Tipo = "CREDITO", Codigo = "00333"},
                new BandeiraPadraoConst() { Nome = "ORGCARD", Tipo = "DEBITO", Codigo = "20207"},
                new BandeiraPadraoConst() { Nome = "SMARTN", Tipo = "CREDITO", Codigo = "00334"},
                new BandeiraPadraoConst() { Nome = "SMARTN", Tipo = "COMBUSTIVEL", Codigo = "10298"},
                new BandeiraPadraoConst() { Nome = "CREDICESTA", Tipo = "CREDITO", Codigo = "00335"},
                new BandeiraPadraoConst() { Nome = "CREDICESTA", Tipo = "DEBITO", Codigo = "20208"},
                new BandeiraPadraoConst() { Nome = "SYSDATA", Tipo = "CREDITO", Codigo = "00230"},
                new BandeiraPadraoConst() { Nome = "SYSDATA", Tipo = "DEBITO", Codigo = "20154"},
                new BandeiraPadraoConst() { Nome = "SYSDATA", Tipo = "VOUCHER", Codigo = "10241"},
                new BandeiraPadraoConst() { Nome = "NUTRICARD", Tipo = "CREDITO", Codigo = "00336"},
                new BandeiraPadraoConst() { Nome = "NUTRICARD", Tipo = "DEBITO", Codigo = "20209"},
                new BandeiraPadraoConst() { Nome = "NUTRICARD", Tipo = "VOUCHER", Codigo = "10154"},
                new BandeiraPadraoConst() { Nome = "FOXWINCARD", Tipo = "CREDITO", Codigo = "00337"},
                new BandeiraPadraoConst() { Nome = "FOXWINCARD", Tipo = "DEBITO", Codigo = "20210"},
                new BandeiraPadraoConst() { Nome = "SOLLUS", Tipo = "COMBUSTIVEL", Codigo = "10299"},
                new BandeiraPadraoConst() { Nome = "SOLLUS", Tipo = "CREDITO", Codigo = "00220"},
                new BandeiraPadraoConst() { Nome = "SOLLUS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10216"},
                new BandeiraPadraoConst() { Nome = "SOLLUS", Tipo = "VOUCHER REFEICAO", Codigo = "10217"},
                new BandeiraPadraoConst() { Nome = "SOFTWAY", Tipo = "CREDITO", Codigo = "00338"},
                new BandeiraPadraoConst() { Nome = "SOFTWAY", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00029"},
                new BandeiraPadraoConst() { Nome = "SQCF", Tipo = "CREDITO", Codigo = "00339"},
                new BandeiraPadraoConst() { Nome = "SQCF", Tipo = "GIFT", Codigo = "10300"},
                new BandeiraPadraoConst() { Nome = "BIGCARD", Tipo = "CREDITO", Codigo = "00142"},
                new BandeiraPadraoConst() { Nome = "BIGCARD", Tipo = "COMBUSTIVEL", Codigo = "10301"},
                new BandeiraPadraoConst() { Nome = "BIGCARD", Tipo = "DEBITO", Codigo = "20211"},
                new BandeiraPadraoConst() { Nome = "BIGCARD", Tipo = "VOUCHER", Codigo = "10195"},
                new BandeiraPadraoConst() { Nome = "JGV", Tipo = "CREDITO", Codigo = "00340"},
                new BandeiraPadraoConst() { Nome = "JGV", Tipo = "DEBITO", Codigo = "20212"},
                new BandeiraPadraoConst() { Nome = "JGV", Tipo = "GIFT", Codigo = "10302"},
                new BandeiraPadraoConst() { Nome = "LIBERCARD", Tipo = "CREDITO", Codigo = "00073"},
                new BandeiraPadraoConst() { Nome = "LIBERCARD", Tipo = "DEBITO", Codigo = "20213"},
                new BandeiraPadraoConst() { Nome = "LIBERCARD", Tipo = "VOUCHER", Codigo = "10077"},
                new BandeiraPadraoConst() { Nome = "MAR", Tipo = "CREDITO", Codigo = "00341"},
                new BandeiraPadraoConst() { Nome = "CSF", Tipo = "CREDITO", Codigo = "00342"},
                new BandeiraPadraoConst() { Nome = "CSF", Tipo = "DEBITO", Codigo = "20214"},
                new BandeiraPadraoConst() { Nome = "SENFF", Tipo = "CREDITO", Codigo = "10155"},
                new BandeiraPadraoConst() { Nome = "SENFF", Tipo = "COMBUSTIVEL", Codigo = "10303"},
                new BandeiraPadraoConst() { Nome = "SENFF", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10169"},
                new BandeiraPadraoConst() { Nome = "SENFF", Tipo = "VOUCHER REFEICAO", Codigo = "10170"},
                new BandeiraPadraoConst() { Nome = "SENFF", Tipo = "VOUCHER", Codigo = "10171"},
                new BandeiraPadraoConst() { Nome = "PRATICARD", Tipo = "CREDITO", Codigo = "00343"},
                new BandeiraPadraoConst() { Nome = "SYSPROCARD", Tipo = "CREDITO", Codigo = "00344"},
                new BandeiraPadraoConst() { Nome = "AUTOEXPRESSO", Tipo = "CREDITO", Codigo = "00345"},
                new BandeiraPadraoConst() { Nome = "NOVOCARD", Tipo = "CREDITO", Codigo = "00346"},
                new BandeiraPadraoConst() { Nome = "CONSIGNUM", Tipo = "CREDITO", Codigo = "00347"},
                new BandeiraPadraoConst() { Nome = "METTACARD", Tipo = "CREDITO", Codigo = "00348"},
                new BandeiraPadraoConst() { Nome = "FLEETCOR", Tipo = "CREDITO", Codigo = "00349"},
                new BandeiraPadraoConst() { Nome = "FLEETCOR", Tipo = "DEBITO", Codigo = "20215"},
                new BandeiraPadraoConst() { Nome = "FLEETCOR", Tipo = "COMBUSTIVEL", Codigo = "10304"},
                new BandeiraPadraoConst() { Nome = "SOROVALE", Tipo = "DEBITO", Codigo = "20216"},
                new BandeiraPadraoConst() { Nome = "UNIMAIS", Tipo = "CREDITO", Codigo = "00350"},
                new BandeiraPadraoConst() { Nome = "ACEITO", Tipo = "CREDITO", Codigo = "00351"},
                new BandeiraPadraoConst() { Nome = "ZAFFARI", Tipo = "CREDITO", Codigo = "00352"},
                new BandeiraPadraoConst() { Nome = "ATUALGROUP", Tipo = "CREDITO", Codigo = "00353"},
                new BandeiraPadraoConst() { Nome = "ATUALGROUP", Tipo = "DEBITO", Codigo = "20217"},
                new BandeiraPadraoConst() { Nome = "LECCACOND", Tipo = "CREDITO", Codigo = "00354"},
                new BandeiraPadraoConst() { Nome = "ORBITALL", Tipo = "CREDITO", Codigo = "00355"},
                new BandeiraPadraoConst() { Nome = "TECBAN", Tipo = "CREDITO", Codigo = "00356"},
                new BandeiraPadraoConst() { Nome = "TECBAN", Tipo = "DEBITO", Codigo = "20218"},
                new BandeiraPadraoConst() { Nome = "GETNET", Tipo = "CREDITO", Codigo = "00357"},
                new BandeiraPadraoConst() { Nome = "GETNET", Tipo = "DEBITO", Codigo = "20219"},
                new BandeiraPadraoConst() { Nome = "FIDELIDADE MAIS", Tipo = "CREDITO", Codigo = "00358"},
                new BandeiraPadraoConst() { Nome = "EPAY", Tipo = "GIFT", Codigo = "10305"},
                new BandeiraPadraoConst() { Nome = "EPAY", Tipo = "DEBITO", Codigo = "20220"},
                new BandeiraPadraoConst() { Nome = "FANCARD", Tipo = "CREDITO", Codigo = "00359"},
                new BandeiraPadraoConst() { Nome = "FANCARD", Tipo = "COMBUSTIVEL", Codigo = "10306"},
                new BandeiraPadraoConst() { Nome = "TELENET", Tipo = "CREDITO", Codigo = "00121"},
                new BandeiraPadraoConst() { Nome = "TELENET", Tipo = "VOUCHER", Codigo = "10122"},
                new BandeiraPadraoConst() { Nome = "TELENET", Tipo = "COMBUSTIVEL", Codigo = "10123"},
                new BandeiraPadraoConst() { Nome = "TELENET", Tipo = "DEBITO", Codigo = "20137"},
                new BandeiraPadraoConst() { Nome = "BONUS CARREFOUR", Tipo = "DEBITO", Codigo = "20221"},
                new BandeiraPadraoConst() { Nome = "IBI", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00360"},
                new BandeiraPadraoConst() { Nome = "CONDUCTOR", Tipo = "CREDITO", Codigo = "00361"},
                new BandeiraPadraoConst() { Nome = "BRADESCO PRIVATE LABEL", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00362"},
                new BandeiraPadraoConst() { Nome = "MAXXICARD", Tipo = "CREDITO", Codigo = "20073"},
                new BandeiraPadraoConst() { Nome = "MAXXICARD", Tipo = "DEBITO", Codigo = "20072"},
                new BandeiraPadraoConst() { Nome = "MAXXICARD", Tipo = "GIFT", Codigo = "20074"},
                new BandeiraPadraoConst() { Nome = "MAXXICARD", Tipo = "COMBUSTIVEL", Codigo = "20075"},
                new BandeiraPadraoConst() { Nome = "MAXXVAN", Tipo = "CREDITO", Codigo = "00105"},
                new BandeiraPadraoConst() { Nome = "MAXXVAN", Tipo = "DEBITO", Codigo = "20106"},
                new BandeiraPadraoConst() { Nome = "GR CARD", Tipo = "CREDITO", Codigo = "00363"},
                new BandeiraPadraoConst() { Nome = "GR CARD", Tipo = "DEBITO", Codigo = "20222"},
                new BandeiraPadraoConst() { Nome = "LIDERCARD", Tipo = "CREDITO", Codigo = "00364"},
                new BandeiraPadraoConst() { Nome = "LIDERCARD", Tipo = "DEBITO", Codigo = "20223"},
                new BandeiraPadraoConst() { Nome = "SINCARD", Tipo = "CREDITO", Codigo = "00365"},
                new BandeiraPadraoConst() { Nome = "SINCARD", Tipo = "DEBITO", Codigo = "20224"},
                new BandeiraPadraoConst() { Nome = "SINDPLUS", Tipo = "CREDITO", Codigo = "00366"},
                new BandeiraPadraoConst() { Nome = "SINDPLUS", Tipo = "DEBITO", Codigo = "20225"},
                new BandeiraPadraoConst() { Nome = "SINDPLUS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10307"},
                new BandeiraPadraoConst() { Nome = "SINDPLUS", Tipo = "VOUCHER", Codigo = "10156"},
                new BandeiraPadraoConst() { Nome = "TOTALCARD", Tipo = "CREDITO", Codigo = "00367"},
                new BandeiraPadraoConst() { Nome = "TOTALCARD", Tipo = "DEBITO", Codigo = "20226"},
                new BandeiraPadraoConst() { Nome = "UNIRCARD", Tipo = "CREDITO", Codigo = "00368"},
                new BandeiraPadraoConst() { Nome = "UNIRCARD", Tipo = "DEBITO", Codigo = "20227"},
                new BandeiraPadraoConst() { Nome = "USECARD", Tipo = "CREDITO", Codigo = "00369"},
                new BandeiraPadraoConst() { Nome = "USECARD", Tipo = "DEBITO", Codigo = "20228"},
                new BandeiraPadraoConst() { Nome = "USECARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10308"},
                new BandeiraPadraoConst() { Nome = "USECARD", Tipo = "VOUCHER REFEICAO", Codigo = "10309"},
                new BandeiraPadraoConst() { Nome = "CAJUCARD", Tipo = "CREDITO", Codigo = "00370"},
                new BandeiraPadraoConst() { Nome = "CAJUCARD", Tipo = "DEBITO", Codigo = "20229"},
                new BandeiraPadraoConst() { Nome = "CONVENIOS CARD", Tipo = "CREDITO", Codigo = "00145"},
                new BandeiraPadraoConst() { Nome = "CONVENIOS CARD", Tipo = "DEBITO", Codigo = "20230"},
                new BandeiraPadraoConst() { Nome = "CONVENIOS CARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10310"},
                new BandeiraPadraoConst() { Nome = "CONVENIOS CARD", Tipo = "VOUCHER", Codigo = "10147"},
                new BandeiraPadraoConst() { Nome = "FRANCARD", Tipo = "CREDITO", Codigo = "00371"},
                new BandeiraPadraoConst() { Nome = "FRANCARD", Tipo = "DEBITO", Codigo = "20231"},
                new BandeiraPadraoConst() { Nome = "SINDCRED", Tipo = "CREDITO", Codigo = "00372"},
                new BandeiraPadraoConst() { Nome = "SINDCRED", Tipo = "DEBITO", Codigo = "20232"},
                new BandeiraPadraoConst() { Nome = "VIACARD", Tipo = "CREDITO", Codigo = "00373"},
                new BandeiraPadraoConst() { Nome = "VIACARD", Tipo = "DEBITO", Codigo = "20233"},
                new BandeiraPadraoConst() { Nome = "ASFEL", Tipo = "CREDITO", Codigo = "00374"},
                new BandeiraPadraoConst() { Nome = "ASFEL", Tipo = "DEBITO", Codigo = "20234"},
                new BandeiraPadraoConst() { Nome = "ATFPMB", Tipo = "CREDITO", Codigo = "00375"},
                new BandeiraPadraoConst() { Nome = "ATFPMB", Tipo = "DEBITO", Codigo = "20235"},
                new BandeiraPadraoConst() { Nome = "CRED VIP", Tipo = "CREDITO", Codigo = "00376"},
                new BandeiraPadraoConst() { Nome = "CRED VIP", Tipo = "DEBITO", Codigo = "20236"},
                new BandeiraPadraoConst() { Nome = "ASSOMISE CARD", Tipo = "CREDITO", Codigo = "00377"},
                new BandeiraPadraoConst() { Nome = "ASSOMISE CARD", Tipo = "DEBITO", Codigo = "20237"},
                new BandeiraPadraoConst() { Nome = "ACSPMESP", Tipo = "CREDITO", Codigo = "00378"},
                new BandeiraPadraoConst() { Nome = "ACSPMESP", Tipo = "DEBITO", Codigo = "20238"},
                new BandeiraPadraoConst() { Nome = "008 CARDS", Tipo = "CREDITO", Codigo = "00379"},
                new BandeiraPadraoConst() { Nome = "008 CARDS", Tipo = "DEBITO", Codigo = "20239"},
                new BandeiraPadraoConst() { Nome = "008 CARDS", Tipo = "COMBUSTIVEL FROTA", Codigo = "10376"},
                new BandeiraPadraoConst() { Nome = "008 CARDS", Tipo = "VOUCHER", Codigo = "10377"},
                new BandeiraPadraoConst() { Nome = "008 CARDS", Tipo = "VOUCHER REFEICAO", Codigo = "10378"},
                new BandeiraPadraoConst() { Nome = "008 CARDS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10379"},
                new BandeiraPadraoConst() { Nome = "DMTPLUS", Tipo = "CREDITO", Codigo = "00380"},
                new BandeiraPadraoConst() { Nome = "DMTPLUS", Tipo = "DEBITO", Codigo = "20240"},
                new BandeiraPadraoConst() { Nome = "GLOBAL CARD", Tipo = "CREDITO", Codigo = "00381"},
                new BandeiraPadraoConst() { Nome = "GLOBAL CARD", Tipo = "DEBITO", Codigo = "20241"},
                new BandeiraPadraoConst() { Nome = "TRINNUS", Tipo = "CREDITO", Codigo = "00382"},
                new BandeiraPadraoConst() { Nome = "TRINNUS", Tipo = "DEBITO", Codigo = "20242"},
                new BandeiraPadraoConst() { Nome = "TRINNUS", Tipo = "COMBUSTIVEL", Codigo = "10311"},
                new BandeiraPadraoConst() { Nome = "FORTE CARD", Tipo = "CREDITO", Codigo = "00383"},
                new BandeiraPadraoConst() { Nome = "FORTE CARD", Tipo = "DEBITO", Codigo = "20243"},
                new BandeiraPadraoConst() { Nome = "SIMEC", Tipo = "CREDITO", Codigo = "00384"},
                new BandeiraPadraoConst() { Nome = "QUALIDADE", Tipo = "CREDITO", Codigo = "00385"},
                new BandeiraPadraoConst() { Nome = "ABRAPETITE", Tipo = "CREDITO", Codigo = "00386"},
                new BandeiraPadraoConst() { Nome = "ABRAPETITE", Tipo = "VOUCHER REFEICAO", Codigo = "10312"},
                new BandeiraPadraoConst() { Nome = "ABRAPETITE", Tipo = "VOUCHER", Codigo = "10142"},
                new BandeiraPadraoConst() { Nome = "ABRAPETITE", Tipo = "DEBITO", Codigo = "20180"},
                new BandeiraPadraoConst() { Nome = "ALLIANCE", Tipo = "CREDITO", Codigo = "00387"},
                new BandeiraPadraoConst() { Nome = "CITY BUSINESS", Tipo = "CREDITO", Codigo = "00388"},
                new BandeiraPadraoConst() { Nome = "CONVENICARD", Tipo = "CREDITO", Codigo = "00389"},
                new BandeiraPadraoConst() { Nome = "DROGABELLA", Tipo = "CREDITO", Codigo = "00390"},
                new BandeiraPadraoConst() { Nome = "FLEXOCARD", Tipo = "CREDITO", Codigo = "00391"},
                new BandeiraPadraoConst() { Nome = "HUGCARDS", Tipo = "CREDITO", Codigo = "00392"},
                new BandeiraPadraoConst() { Nome = "QUATROCARD", Tipo = "CREDITO", Codigo = "00393"},
                new BandeiraPadraoConst() { Nome = "ROMCARD", Tipo = "CREDITO", Codigo = "00394"},
                new BandeiraPadraoConst() { Nome = "ROMCARD", Tipo = "DEBITO", Codigo = "20184"},
                new BandeiraPadraoConst() { Nome = "ROMCARD", Tipo = "VOUCHER", Codigo = "10264"},
                new BandeiraPadraoConst() { Nome = "SYSTEMCARD", Tipo = "CREDITO", Codigo = "00395"},
                new BandeiraPadraoConst() { Nome = "UNOCARD", Tipo = "CREDITO", Codigo = "00396"},
                new BandeiraPadraoConst() { Nome = "UTILIZECARDS", Tipo = "CREDITO", Codigo = "00397"},
                new BandeiraPadraoConst() { Nome = "UTILIZECARDS", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00398"},
                new BandeiraPadraoConst() { Nome = "VERYCARD", Tipo = "CREDITO", Codigo = "00399"},
                new BandeiraPadraoConst() { Nome = "VMX", Tipo = "CREDITO", Codigo = "00400"},
                new BandeiraPadraoConst() { Nome = "AUTOCRED CARD", Tipo = "CREDITO", Codigo = "00401"},
                new BandeiraPadraoConst() { Nome = "BLUECASH", Tipo = "CREDITO", Codigo = "00402"},
                new BandeiraPadraoConst() { Nome = "MICROMOB", Tipo = "CREDITO", Codigo = "00403"},
                new BandeiraPadraoConst() { Nome = "QUALICARD", Tipo = "CREDITO", Codigo = "00404"},
                new BandeiraPadraoConst() { Nome = "QUALICARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00405"},
                new BandeiraPadraoConst() { Nome = "SIAPNET", Tipo = "CREDITO", Codigo = "00155"},
                new BandeiraPadraoConst() { Nome = "SIAPNET", Tipo = "DEBITO", Codigo = "20136"},
                new BandeiraPadraoConst() { Nome = "SIAPNET", Tipo = "VOUCHER", Codigo = "10232"},
                new BandeiraPadraoConst() { Nome = "SIAPNET", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10233"},
                new BandeiraPadraoConst() { Nome = "SIAPNET", Tipo = "VOUCHER REFEICAO", Codigo = "10234"},
                new BandeiraPadraoConst() { Nome = "SIAPNET", Tipo = "COMBUSTIVEL", Codigo = "10235"},
                new BandeiraPadraoConst() { Nome = "SIAPNET", Tipo = "COMBUSTIVEL FROTA", Codigo = "10236"},
                new BandeiraPadraoConst() { Nome = "SIAPNET", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00229"},
                new BandeiraPadraoConst() { Nome = "SIAPNET", Tipo = "DEBITO PRIVATE LABEL", Codigo = "20157"},
                new BandeiraPadraoConst() { Nome = "ATACADAO", Tipo = "CREDITO", Codigo = "00163"},
                new BandeiraPadraoConst() { Nome = "CARREFOUR", Tipo = "CREDITO", Codigo = "00164"},
                new BandeiraPadraoConst() { Nome = "APOLOCARD", Tipo = "CREDITO", Codigo = "00095"},
                new BandeiraPadraoConst() { Nome = "GLOBALCOOPER", Tipo = "CREDITO", Codigo = "00096"},
                new BandeiraPadraoConst() { Nome = "PRATI", Tipo = "CREDITO", Codigo = "00097"},
                new BandeiraPadraoConst() { Nome = "SUPPERCARD", Tipo = "CREDITO", Codigo = "00098"},
                new BandeiraPadraoConst() { Nome = "QUALITA", Tipo = "CREDITO", Codigo = "00099"},
                new BandeiraPadraoConst() { Nome = "QUALITA", Tipo = "GIFT", Codigo = "10100"},
                new BandeiraPadraoConst() { Nome = "TECBIZ", Tipo = "CREDITO", Codigo = "00101"},
                new BandeiraPadraoConst() { Nome = "TODO", Tipo = "CREDITO", Codigo = "00102"},
                new BandeiraPadraoConst() { Nome = "TODO", Tipo = "GIFT", Codigo = "10103"},
                new BandeiraPadraoConst() { Nome = "VECELLCARD", Tipo = "CREDITO", Codigo = "00104"},
                new BandeiraPadraoConst() { Nome = "ACCENTIV", Tipo = "CREDITO", Codigo = "00107"},
                new BandeiraPadraoConst() { Nome = "ASPEB", Tipo = "CREDITO", Codigo = "00108"},
                new BandeiraPadraoConst() { Nome = "VALE EXPRESS", Tipo = "CREDITO", Codigo = "00109"},
                new BandeiraPadraoConst() { Nome = "VALE EXPRESS", Tipo = "VOUCHER", Codigo = "10110"},
                new BandeiraPadraoConst() { Nome = "VALE EXPRESS", Tipo = "DEBITO", Codigo = "20111"},
                new BandeiraPadraoConst() { Nome = "GOLDICARD", Tipo = "COMBUSTIVEL", Codigo = "10112"},
                new BandeiraPadraoConst() { Nome = "FLEETCARD", Tipo = "COMBUSTIVEL", Codigo = "10113"},
                new BandeiraPadraoConst() { Nome = "FLEETCARD", Tipo = "VOUCHER", Codigo = "10152"},
                new BandeiraPadraoConst() { Nome = "DAYCARD", Tipo = "CREDITO", Codigo = "00114"},
                new BandeiraPadraoConst() { Nome = "DAYCARD", Tipo = "DEBITO", Codigo = "20115"},
                new BandeiraPadraoConst() { Nome = "HUBPREPAID", Tipo = "VOUCHER", Codigo = "10116"},
                new BandeiraPadraoConst() { Nome = "HUBPREPAID", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10313"},
                new BandeiraPadraoConst() { Nome = "HUBPREPAID", Tipo = "VOUCHER REFEICAO", Codigo = "10314"},
                new BandeiraPadraoConst() { Nome = "FLEXFROTA", Tipo = "COMBUSTIVEL", Codigo = "10117"},
                new BandeiraPadraoConst() { Nome = "RVCARDS", Tipo = "CREDITO", Codigo = "00118"},
                new BandeiraPadraoConst() { Nome = "LEADER", Tipo = "CREDITO", Codigo = "00119"},
                new BandeiraPadraoConst() { Nome = "LEADER", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00450"},
                new BandeiraPadraoConst() { Nome = "CONVENIOFACIL", Tipo = "CREDITO", Codigo = "20120"},
                new BandeiraPadraoConst() { Nome = "TICKETLOG", Tipo = "CREDITO", Codigo = "00124"},
                new BandeiraPadraoConst() { Nome = "TICKETLOG", Tipo = "COMBUSTIVEL", Codigo = "10125"},
                new BandeiraPadraoConst() { Nome = "TICKETLOG", Tipo = "DEBITO", Codigo = "20126"},
                new BandeiraPadraoConst() { Nome = "VELOE", Tipo = "COMBUSTIVEL", Codigo = "10136"},
                new BandeiraPadraoConst() { Nome = "PAGSIMPLES", Tipo = "CREDITO", Codigo = "00131"},
                new BandeiraPadraoConst() { Nome = "VOXCRED", Tipo = "CREDITO", Codigo = "00138"},
                new BandeiraPadraoConst() { Nome = "WIZEO", Tipo = "COMBUSTIVEL", Codigo = "10139"},
                new BandeiraPadraoConst() { Nome = "BORBANET", Tipo = "CREDITO", Codigo = "00140"},
                new BandeiraPadraoConst() { Nome = "PERSONALIDADE CARD", Tipo = "CREDITO", Codigo = "00157"},
                new BandeiraPadraoConst() { Nome = "RG CARD", Tipo = "CREDITO", Codigo = "00158"},
                new BandeiraPadraoConst() { Nome = "TAURUS CARD", Tipo = "CREDITO", Codigo = "00159"},
                new BandeiraPadraoConst() { Nome = "BEN VISAVALE", Tipo = "VOUCHER REFEICAO", Codigo = "10140"},
                new BandeiraPadraoConst() { Nome = "BEN VISAVALE", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10141"},
                new BandeiraPadraoConst() { Nome = "BEN VISAVALE", Tipo = "VOUCHER", Codigo = "10315"},
                new BandeiraPadraoConst() { Nome = "AVANCARD", Tipo = "VOUCHER", Codigo = "10143"},
                new BandeiraPadraoConst() { Nome = "AVANCARD", Tipo = "CREDITO", Codigo = "00266"},
                new BandeiraPadraoConst() { Nome = "BONUSCRED", Tipo = "CREDITO", Codigo = "00143"},
                new BandeiraPadraoConst() { Nome = "BONUSCRED", Tipo = "VOUCHER", Codigo = "10146"},
                new BandeiraPadraoConst() { Nome = "CREDIALIMENTACAO", Tipo = "VOUCHER", Codigo = "10149"},
                new BandeiraPadraoConst() { Nome = "DIAMANTE CARD", Tipo = "CREDITO", Codigo = "00147"},
                new BandeiraPadraoConst() { Nome = "EUCARD", Tipo = "VOUCHER", Codigo = "10150"},
                new BandeiraPadraoConst() { Nome = "EUCARD", Tipo = "CREDITO", Codigo = "00267"},
                new BandeiraPadraoConst() { Nome = "EUCARD", Tipo = "DEBITO", Codigo = "20185"},
                new BandeiraPadraoConst() { Nome = "FACECARD", Tipo = "VOUCHER", Codigo = "10151"},
                new BandeiraPadraoConst() { Nome = "FACECARD", Tipo = "CREDITO", Codigo = "00270"},
                new BandeiraPadraoConst() { Nome = "FACECARD", Tipo = "DEBITO", Codigo = "20187"},
                new BandeiraPadraoConst() { Nome = "JET CARD", Tipo = "CREDITO", Codigo = "00149"},
                new BandeiraPadraoConst() { Nome = "LECARD", Tipo = "VOUCHER", Codigo = "10153"},
                new BandeiraPadraoConst() { Nome = "LECARD", Tipo = "CREDITO", Codigo = "00262"},
                new BandeiraPadraoConst() { Nome = "ONECARD", Tipo = "CREDITO", Codigo = "00150"},
                new BandeiraPadraoConst() { Nome = "ONECARD", Tipo = "COMBUSTIVEL FROTA", Codigo = "10375"},
                new BandeiraPadraoConst() { Nome = "PERSONALCARD", Tipo = "CREDITO", Codigo = "00151"},
                new BandeiraPadraoConst() { Nome = "PERSONALCARD", Tipo = "DEBITO", Codigo = "20141"},
                new BandeiraPadraoConst() { Nome = "PERSONALCARD", Tipo = "VOUCHER", Codigo = "10182"},
                new BandeiraPadraoConst() { Nome = "PERSONALCARD", Tipo = "VOUCHER REFEICAO", Codigo = "10368"},
                new BandeiraPadraoConst() { Nome = "PERSONALCARD", Tipo = "COMBUSTIVEL", Codigo = "10369"},
                new BandeiraPadraoConst() { Nome = "PERSONALCARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10373"},
                new BandeiraPadraoConst() { Nome = "SYSTEM FARMA", Tipo = "CREDITO", Codigo = "00152"},
                new BandeiraPadraoConst() { Nome = "VS CARD", Tipo = "VOUCHER", Codigo = "10160"},
                new BandeiraPadraoConst() { Nome = "VS CARD", Tipo = "CREDITO", Codigo = "00248"},
                new BandeiraPadraoConst() { Nome = "VS CARD", Tipo = "DEBITO", Codigo = "20165"},
                new BandeiraPadraoConst() { Nome = "LIV", Tipo = "CREDITO", Codigo = "00153"},
                new BandeiraPadraoConst() { Nome = "LIV", Tipo = "DEBITO", Codigo = "20134"},
                new BandeiraPadraoConst() { Nome = "ROTACARD", Tipo = "COMBUSTIVEL", Codigo = "10161"},
                new BandeiraPadraoConst() { Nome = "SINDSPAM", Tipo = "CREDITO", Codigo = "00156"},
                new BandeiraPadraoConst() { Nome = "SINDSPAM", Tipo = "DEBITO", Codigo = "20138"},
                new BandeiraPadraoConst() { Nome = "AVBR", Tipo = "CREDITO", Codigo = "00166"},
                new BandeiraPadraoConst() { Nome = "AVBR", Tipo = "DEBITO", Codigo = "20244"},
                new BandeiraPadraoConst() { Nome = "VUON", Tipo = "CREDITO", Codigo = "00167"},
                new BandeiraPadraoConst() { Nome = "CREDCESTA", Tipo = "CREDITO", Codigo = "00168"},
                new BandeiraPadraoConst() { Nome = "LIFECARD", Tipo = "CREDITO", Codigo = "00170"},
                new BandeiraPadraoConst() { Nome = "LIFECARD", Tipo = "DEBITO", Codigo = "20142"},
                new BandeiraPadraoConst() { Nome = "LIFECARD", Tipo = "VOUCHER", Codigo = "10183"},
                new BandeiraPadraoConst() { Nome = "TRIOCARD", Tipo = "CREDITO", Codigo = "00171"},
                new BandeiraPadraoConst() { Nome = "TRIOCARD", Tipo = "DEBITO", Codigo = "20143"},
                new BandeiraPadraoConst() { Nome = "TRIOCARD", Tipo = "VOUCHER", Codigo = "10184"},
                new BandeiraPadraoConst() { Nome = "BRASIL CONVENIOS", Tipo = "CREDITO", Codigo = "00174"},
                new BandeiraPadraoConst() { Nome = "BRASIL CONVENIOS", Tipo = "DEBITO", Codigo = "20146"},
                new BandeiraPadraoConst() { Nome = "CDC CARD", Tipo = "CREDITO", Codigo = "00175"},
                new BandeiraPadraoConst() { Nome = "CDC CARD", Tipo = "DEBITO", Codigo = "20147"},
                new BandeiraPadraoConst() { Nome = "GRAALCARD", Tipo = "CREDITO", Codigo = "00176"},
                new BandeiraPadraoConst() { Nome = "GRAALCARD", Tipo = "DEBITO", Codigo = "20148"},
                new BandeiraPadraoConst() { Nome = "GRANDCARD", Tipo = "CREDITO", Codigo = "00177"},
                new BandeiraPadraoConst() { Nome = "GRANDCARD", Tipo = "DEBITO", Codigo = "20149"},
                new BandeiraPadraoConst() { Nome = "ITACARD", Tipo = "CREDITO", Codigo = "00178"},
                new BandeiraPadraoConst() { Nome = "ITACARD", Tipo = "DEBITO", Codigo = "20150"},
                new BandeiraPadraoConst() { Nome = "REDEMED", Tipo = "CREDITO", Codigo = "00179"},
                new BandeiraPadraoConst() { Nome = "ECXCARD", Tipo = "CREDITO", Codigo = "00181"},
                new BandeiraPadraoConst() { Nome = "ECXCARD", Tipo = "COMBUSTIVEL FROTA", Codigo = "10186"},
                new BandeiraPadraoConst() { Nome = "TRUCKPAG", Tipo = "COMBUSTIVEL", Codigo = "10187"},
                new BandeiraPadraoConst() { Nome = "DOTZ", Tipo = "CREDITO", Codigo = "00182"},
                new BandeiraPadraoConst() { Nome = "DOTZ", Tipo = "DEBITO", Codigo = "20153"},
                new BandeiraPadraoConst() { Nome = "ACICREDI", Tipo = "CREDITO", Codigo = "00183"},
                new BandeiraPadraoConst() { Nome = "AESP CONVENIO", Tipo = "CREDITO", Codigo = "00184"},
                new BandeiraPadraoConst() { Nome = "AGUIA CARD", Tipo = "CREDITO", Codigo = "00185"},
                new BandeiraPadraoConst() { Nome = "ARCOMCREDICARD", Tipo = "CREDITO", Codigo = "00186"},
                new BandeiraPadraoConst() { Nome = "ASSUFOP CARD", Tipo = "CREDITO", Codigo = "00187"},
                new BandeiraPadraoConst() { Nome = "AVANTISYS", Tipo = "CREDITO", Codigo = "00188"},
                new BandeiraPadraoConst() { Nome = "AZUL CARD", Tipo = "VOUCHER", Codigo = "10190"},
                new BandeiraPadraoConst() { Nome = "BANDCARD", Tipo = "CREDITO", Codigo = "00189"},
                new BandeiraPadraoConst() { Nome = "BANDCARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10191"},
                new BandeiraPadraoConst() { Nome = "BANK", Tipo = "VOUCHER", Codigo = "10193"},
                new BandeiraPadraoConst() { Nome = "BICARTOES", Tipo = "VOUCHER", Codigo = "10194"},
                new BandeiraPadraoConst() { Nome = "BLUEBANK", Tipo = "VOUCHER", Codigo = "10196"},
                new BandeiraPadraoConst() { Nome = "CAMPELOCARD", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10197"},
                new BandeiraPadraoConst() { Nome = "CAMPELOCARD", Tipo = "CREDITO", Codigo = "00190"},
                new BandeiraPadraoConst() { Nome = "CARTAO CONFIANCA", Tipo = "CREDITO", Codigo = "00191"},
                new BandeiraPadraoConst() { Nome = "CARTAO CONFIANCA", Tipo = "VOUCHER", Codigo = "10198"},
                new BandeiraPadraoConst() { Nome = "CARTAO HORTIFRUTI", Tipo = "CREDITO", Codigo = "00192"},
                new BandeiraPadraoConst() { Nome = "IRANI", Tipo = "CREDITO", Codigo = "00193"},
                new BandeiraPadraoConst() { Nome = "IRANI", Tipo = "VOUCHER", Codigo = "10199"},
                new BandeiraPadraoConst() { Nome = "IRANI", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10200"},
                new BandeiraPadraoConst() { Nome = "CARTAO LEVEMAIS", Tipo = "CREDITO", Codigo = "00194"},
                new BandeiraPadraoConst() { Nome = "CARTAO MONTREAL", Tipo = "CREDITO", Codigo = "00195"},
                new BandeiraPadraoConst() { Nome = "CARTAO NALIN", Tipo = "CREDITO", Codigo = "00196"},
                new BandeiraPadraoConst() { Nome = "CARTOES BRAIZINHO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00197"},
                new BandeiraPadraoConst() { Nome = "CATTANCARD", Tipo = "CREDITO", Codigo = "00198"},
                new BandeiraPadraoConst() { Nome = "CATTANCARD FORTBRASIL", Tipo = "CREDITO", Codigo = "00199"},
                new BandeiraPadraoConst() { Nome = "CLUBE DEMAIS", Tipo = "CREDITO", Codigo = "00200"},
                new BandeiraPadraoConst() { Nome = "CLUBE DEMAIS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10201"},
                new BandeiraPadraoConst() { Nome = "COOPECIC CARD", Tipo = "CREDITO", Codigo = "00201"},
                new BandeiraPadraoConst() { Nome = "COOPERATIVO", Tipo = "CREDITO", Codigo = "00202"},
                new BandeiraPadraoConst() { Nome = "CREDIALTO CARD", Tipo = "CREDITO", Codigo = "00203"},
                new BandeiraPadraoConst() { Nome = "CREDINOVA CARD", Tipo = "CREDITO", Codigo = "00204"},
                new BandeiraPadraoConst() { Nome = "CREDIPINHO CARD", Tipo = "CREDITO", Codigo = "00205"},
                new BandeiraPadraoConst() { Nome = "EDIZ", Tipo = "VOUCHER", Codigo = "10203"},
                new BandeiraPadraoConst() { Nome = "ENSCON CARD", Tipo = "VOUCHER", Codigo = "10204"},
                new BandeiraPadraoConst() { Nome = "GIRACARD", Tipo = "VOUCHER", Codigo = "10206"},
                new BandeiraPadraoConst() { Nome = "IDEALCARD", Tipo = "VOUCHER", Codigo = "10207"},
                new BandeiraPadraoConst() { Nome = "IDEALCARD", Tipo = "CREDITO", Codigo = "00249"},
                new BandeiraPadraoConst() { Nome = "IDEALCARD", Tipo = "DEBITO", Codigo = "20166"},
                new BandeiraPadraoConst() { Nome = "IMPERATRIZ", Tipo = "CREDITO", Codigo = "00207"},
                new BandeiraPadraoConst() { Nome = "IMPERATRIZ", Tipo = "VOUCHER", Codigo = "10208"},
                new BandeiraPadraoConst() { Nome = "LAGOACRED CARD", Tipo = "CREDITO", Codigo = "00208"},
                new BandeiraPadraoConst() { Nome = "MAISFACIL", Tipo = "CREDITO", Codigo = "00209"},
                new BandeiraPadraoConst() { Nome = "MAISFACIL", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00237"},
                new BandeiraPadraoConst() { Nome = "NEOCARD", Tipo = "CREDITO", Codigo = "00210"},
                new BandeiraPadraoConst() { Nome = "NEUS", Tipo = "VOUCHER", Codigo = "10209"},
                new BandeiraPadraoConst() { Nome = "NEUS MINAS", Tipo = "VOUCHER", Codigo = "10210"},
                new BandeiraPadraoConst() { Nome = "PAGUEMENOS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10211"},
                new BandeiraPadraoConst() { Nome = "PAGUEMENOS", Tipo = "VOUCHER BENEFICIO", Codigo = "10223"},
                new BandeiraPadraoConst() { Nome = "PG CARD", Tipo = "VOUCHER", Codigo = "10212"},
                new BandeiraPadraoConst() { Nome = "PITCARD", Tipo = "CREDITO", Codigo = "00211"},
                new BandeiraPadraoConst() { Nome = "QUEIROZ PREMIUM", Tipo = "CREDITO", Codigo = "00212"},
                new BandeiraPadraoConst() { Nome = "QUEIROZ PREMIUM", Tipo = "VOUCHER", Codigo = "10213"},
                new BandeiraPadraoConst() { Nome = "QUEIROZ PREMIUM", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10214"},
                new BandeiraPadraoConst() { Nome = "REDE CUIDAR", Tipo = "CREDITO", Codigo = "00213"},
                new BandeiraPadraoConst() { Nome = "SAVEGNAGO", Tipo = "CREDITO", Codigo = "00214"},
                new BandeiraPadraoConst() { Nome = "SERTAO CARD", Tipo = "CREDITO", Codigo = "00215"},
                new BandeiraPadraoConst() { Nome = "SERTAO CARD", Tipo = "VOUCHER BENEFICIO", Codigo = "10226"},
                new BandeiraPadraoConst() { Nome = "SERVIR", Tipo = "CREDITO", Codigo = "00216"},
                new BandeiraPadraoConst() { Nome = "SERVIR", Tipo = "VOUCHER BENEFICIO", Codigo = "10225"},
                new BandeiraPadraoConst() { Nome = "SIACARD", Tipo = "CREDITO", Codigo = "00217"},
                new BandeiraPadraoConst() { Nome = "SIM", Tipo = "CREDITO", Codigo = "00218"},
                new BandeiraPadraoConst() { Nome = "SINDCONVENIOS", Tipo = "VOUCHER", Codigo = "10215"},
                new BandeiraPadraoConst() { Nome = "SITECC", Tipo = "CREDITO", Codigo = "00219"},
                new BandeiraPadraoConst() { Nome = "STILOA CARD", Tipo = "CREDITO", Codigo = "00221"},
                new BandeiraPadraoConst() { Nome = "SUPERCRED", Tipo = "CREDITO", Codigo = "00222"},
                new BandeiraPadraoConst() { Nome = "SUPERCRED", Tipo = "VOUCHER", Codigo = "10218"},
                new BandeiraPadraoConst() { Nome = "TORRA TORRA", Tipo = "CREDITO", Codigo = "00224"},
                new BandeiraPadraoConst() { Nome = "TORRA TORRA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00413"},
                new BandeiraPadraoConst() { Nome = "UAICARD", Tipo = "CREDITO", Codigo = "00225"},
                new BandeiraPadraoConst() { Nome = "VALEMAIS", Tipo = "VOUCHER", Codigo = "10219"},
                new BandeiraPadraoConst() { Nome = "VALEMAIS", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10220"},
                new BandeiraPadraoConst() { Nome = "VALEMAIS", Tipo = "VOUCHER BENEFICIO", Codigo = "10228"},
                new BandeiraPadraoConst() { Nome = "VALEMAIS", Tipo = "CREDITO", Codigo = "00265"},
                new BandeiraPadraoConst() { Nome = "VALEMAIS", Tipo = "DEBITO", Codigo = "20182"},
                new BandeiraPadraoConst() { Nome = "VALLE REAL", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10221"},
                new BandeiraPadraoConst() { Nome = "VALLE REAL", Tipo = "VOUCHER BENEFICIO", Codigo = "10229"},
                new BandeiraPadraoConst() { Nome = "VEGAS", Tipo = "VOUCHER", Codigo = "10222"},
                new BandeiraPadraoConst() { Nome = "VIPCARD", Tipo = "CREDITO", Codigo = "00226"},
                new BandeiraPadraoConst() { Nome = "ZEMA", Tipo = "CREDITO", Codigo = "00227"},
                new BandeiraPadraoConst() { Nome = "ZEMA", Tipo = "DEBITO", Codigo = "20247"},
                new BandeiraPadraoConst() { Nome = "PARACATU CARD", Tipo = "VOUCHER BENEFICIO", Codigo = "10224"},
                new BandeiraPadraoConst() { Nome = "SINTRAM", Tipo = "VOUCHER BENEFICIO", Codigo = "10227"},
                new BandeiraPadraoConst() { Nome = "ACIACCARD", Tipo = "CREDITO", Codigo = "00406"},
                new BandeiraPadraoConst() { Nome = "VALEPRES SYSDATA", Tipo = "GIFT", Codigo = "10239"},
                new BandeiraPadraoConst() { Nome = "VALEPRES PEELA", Tipo = "GIFT", Codigo = "10240"},
                new BandeiraPadraoConst() { Nome = "BRADESCARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00231"},
                new BandeiraPadraoConst() { Nome = "BRADESCARD ELO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00232"},
                new BandeiraPadraoConst() { Nome = "BRADESCARD VISA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00233"},
                new BandeiraPadraoConst() { Nome = "BRADESCARD MASTERCARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00234"},
                new BandeiraPadraoConst() { Nome = "MERCADO PAGO", Tipo = "CARTEIRA DIGITAL", Codigo = "10316"},
                new BandeiraPadraoConst() { Nome = "IZPAY", Tipo = "CARTEIRA DIGITAL", Codigo = "10317"},
                new BandeiraPadraoConst() { Nome = "VEE", Tipo = "CARTEIRA DIGITAL", Codigo = "10318"},
                new BandeiraPadraoConst() { Nome = "MONEYPAG", Tipo = "CARTEIRA DIGITAL", Codigo = "10319"},
                new BandeiraPadraoConst() { Nome = "CIELO", Tipo = "CARTEIRA DIGITAL", Codigo = "10320"},
                new BandeiraPadraoConst() { Nome = "PICPAY", Tipo = "CARTEIRA DIGITAL", Codigo = "10321"},
                new BandeiraPadraoConst() { Nome = "4ALL", Tipo = "CARTEIRA DIGITAL", Codigo = "10322"},
                new BandeiraPadraoConst() { Nome = "TAPAGO", Tipo = "CARTEIRA DIGITAL", Codigo = "10323"},
                new BandeiraPadraoConst() { Nome = "BLACKHAWK", Tipo = "GIFT", Codigo = "10252"},
                new BandeiraPadraoConst() { Nome = "BLACKHAWK", Tipo = "DEBITO PRIVATE LABEL", Codigo = "20155"},
                new BandeiraPadraoConst() { Nome = "GOLDENFARMA", Tipo = "CREDITO", Codigo = "00235"},
                new BandeiraPadraoConst() { Nome = "MEU VALE", Tipo = "CREDITO", Codigo = "00236"},
                new BandeiraPadraoConst() { Nome = "MEU VALE", Tipo = "DEBITO", Codigo = "20156"},
                new BandeiraPadraoConst() { Nome = "ONESMART", Tipo = "VOUCHER", Codigo = "10254"},
                new BandeiraPadraoConst() { Nome = "ONESMART", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10371"},
                new BandeiraPadraoConst() { Nome = "ONESMART", Tipo = "VOUCHER REFEICAO", Codigo = "10372"},
                new BandeiraPadraoConst() { Nome = "CARD IDEAL", Tipo = "COMBUSTIVEL FROTA", Codigo = "10255"},
                new BandeiraPadraoConst() { Nome = "CARD IDEAL", Tipo = "CREDITO", Codigo = "00258"},
                new BandeiraPadraoConst() { Nome = "CARD IDEAL", Tipo = "DEBITO", Codigo = "20175"},
                new BandeiraPadraoConst() { Nome = "TROCO SIMPLES", Tipo = "CARTEIRA DIGITAL", Codigo = "10324"},
                new BandeiraPadraoConst() { Nome = "BEEVALE", Tipo = "CARTEIRA DIGITAL", Codigo = "10325"},
                new BandeiraPadraoConst() { Nome = "BRINKSPAY", Tipo = "CARTEIRA DIGITAL", Codigo = "10326"},
                new BandeiraPadraoConst() { Nome = "PAGBANK", Tipo = "CARTEIRA DIGITAL", Codigo = "10327"},
                new BandeiraPadraoConst() { Nome = "ORO", Tipo = "CARTEIRA DIGITAL", Codigo = "10328"},
                new BandeiraPadraoConst() { Nome = "CONNECTYPAY", Tipo = "CARTEIRA DIGITAL", Codigo = "10256"},
                new BandeiraPadraoConst() { Nome = "ABM CASH", Tipo = "CARTEIRA DIGITAL", Codigo = "10257"},
                new BandeiraPadraoConst() { Nome = "UAUH", Tipo = "CREDITO", Codigo = "00239"},
                new BandeiraPadraoConst() { Nome = "UAUH", Tipo = "COMBUSTIVEL FROTA", Codigo = "10258"},
                new BandeiraPadraoConst() { Nome = "UAUH", Tipo = "VOUCHER ALIMENTACAO", Codigo = "10259"},
                new BandeiraPadraoConst() { Nome = "UAUH", Tipo = "VOUCHER REFEICAO", Codigo = "10260"},
                new BandeiraPadraoConst() { Nome = "UAUH", Tipo = "VOUCHER FARMACIA", Codigo = "10261"},
                new BandeiraPadraoConst() { Nome = "UAUH", Tipo = "VOUCHER", Codigo = "10262"},
                new BandeiraPadraoConst() { Nome = "BRASILCARD", Tipo = "CREDITO", Codigo = "00240"},
                new BandeiraPadraoConst() { Nome = "MGCARD", Tipo = "CREDITO", Codigo = "00245"},
                new BandeiraPadraoConst() { Nome = "MGCARD", Tipo = "DEBITO", Codigo = "20162"},
                new BandeiraPadraoConst() { Nome = "BOA CONVENIOS", Tipo = "CREDITO", Codigo = "00242"},
                new BandeiraPadraoConst() { Nome = "BOA CONVENIOS", Tipo = "DEBITO", Codigo = "20159"},
                new BandeiraPadraoConst() { Nome = "CREDFACIL", Tipo = "CREDITO", Codigo = "00243"},
                new BandeiraPadraoConst() { Nome = "CREDFACIL", Tipo = "DEBITO", Codigo = "20160"},
                new BandeiraPadraoConst() { Nome = "ASCIPAM", Tipo = "CREDITO", Codigo = "00244"},
                new BandeiraPadraoConst() { Nome = "ASCIPAM", Tipo = "DEBITO", Codigo = "20161"},
                new BandeiraPadraoConst() { Nome = "QCARD", Tipo = "CREDITO", Codigo = "00246"},
                new BandeiraPadraoConst() { Nome = "QCARD", Tipo = "DEBITO", Codigo = "20163"},
                new BandeiraPadraoConst() { Nome = "SIAPNET IDEAL", Tipo = "CREDITO", Codigo = "00241"},
                new BandeiraPadraoConst() { Nome = "SIAPNET IDEAL", Tipo = "DEBITO", Codigo = "20158"},
                new BandeiraPadraoConst() { Nome = "COOPELIFE", Tipo = "CREDITO", Codigo = "00247"},
                new BandeiraPadraoConst() { Nome = "COOPELIFE", Tipo = "DEBITO", Codigo = "20164"},
                new BandeiraPadraoConst() { Nome = "FAMILLY", Tipo = "CREDITO", Codigo = "00250"},
                new BandeiraPadraoConst() { Nome = "FAMILLY", Tipo = "DEBITO", Codigo = "20167"},
                new BandeiraPadraoConst() { Nome = "CREDPUBLICO", Tipo = "CREDITO", Codigo = "00251"},
                new BandeiraPadraoConst() { Nome = "CREDPUBLICO", Tipo = "DEBITO", Codigo = "20168"},
                new BandeiraPadraoConst() { Nome = "MURY", Tipo = "CREDITO", Codigo = "00252"},
                new BandeiraPadraoConst() { Nome = "MURY", Tipo = "DEBITO", Codigo = "20169"},
                new BandeiraPadraoConst() { Nome = "MASTERPLUS", Tipo = "CREDITO", Codigo = "00253"},
                new BandeiraPadraoConst() { Nome = "MASTERPLUS", Tipo = "DEBITO", Codigo = "20170"},
                new BandeiraPadraoConst() { Nome = "CLUBECAMPO", Tipo = "CREDITO", Codigo = "00255"},
                new BandeiraPadraoConst() { Nome = "CLUBECAMPO", Tipo = "DEBITO", Codigo = "20172"},
                new BandeiraPadraoConst() { Nome = "NUTRICHECK", Tipo = "CREDITO", Codigo = "00256"},
                new BandeiraPadraoConst() { Nome = "NUTRICHECK", Tipo = "DEBITO", Codigo = "20173"},
                new BandeiraPadraoConst() { Nome = "SOULCARD", Tipo = "CREDITO", Codigo = "00257"},
                new BandeiraPadraoConst() { Nome = "SOULCARD", Tipo = "DEBITO", Codigo = "20174"},
                new BandeiraPadraoConst() { Nome = "ULTRACRED", Tipo = "CREDITO", Codigo = "00259"},
                new BandeiraPadraoConst() { Nome = "ULTRACRED", Tipo = "DEBITO", Codigo = "20176"},
                new BandeiraPadraoConst() { Nome = "PILARCRED", Tipo = "CREDITO", Codigo = "00260"},
                new BandeiraPadraoConst() { Nome = "PILARCRED", Tipo = "DEBITO", Codigo = "20177"},
                new BandeiraPadraoConst() { Nome = "SAMERICA", Tipo = "CREDITO", Codigo = "00261"},
                new BandeiraPadraoConst() { Nome = "SAMERICA", Tipo = "DEBITO", Codigo = "20178"},
                new BandeiraPadraoConst() { Nome = "CIELO QR CODE", Tipo = "CREDITO", Codigo = "00263"},
                new BandeiraPadraoConst() { Nome = "CIELO QR CODE", Tipo = "DEBITO", Codigo = "20179"},
                new BandeiraPadraoConst() { Nome = "CROSCARD", Tipo = "CREDITO", Codigo = "00264"},
                new BandeiraPadraoConst() { Nome = "SANCARD", Tipo = "CREDITO", Codigo = "00268"},
                new BandeiraPadraoConst() { Nome = "SANCARD", Tipo = "DEBITO", Codigo = "20186"},
                new BandeiraPadraoConst() { Nome = "BAMEX", Tipo = "VOUCHER", Codigo = "10329"},
                new BandeiraPadraoConst() { Nome = "BAMEX", Tipo = "COMBUSTIVEL FROTA", Codigo = "10330"},
                new BandeiraPadraoConst() { Nome = "VIASOFTPAY", Tipo = "VOUCHER", Codigo = "10331"},
                new BandeiraPadraoConst() { Nome = "VIASOFTPAY", Tipo = "CREDITO", Codigo = "00477"},
                new BandeiraPadraoConst() { Nome = "DIBS", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00409"},
                new BandeiraPadraoConst() { Nome = "KALLAN", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00410"},
                new BandeiraPadraoConst() { Nome = "ED", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00411"},
                new BandeiraPadraoConst() { Nome = "SHOEBIZ", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00412"},
                new BandeiraPadraoConst() { Nome = "KHELF", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00414"},
                new BandeiraPadraoConst() { Nome = "MUITO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00415"},
                new BandeiraPadraoConst() { Nome = "DI GASPI", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00416"},
                new BandeiraPadraoConst() { Nome = "PONTAL CARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00417"},
                new BandeiraPadraoConst() { Nome = "HUMANITARIAN", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00418"},
                new BandeiraPadraoConst() { Nome = "NOVO MUNDO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00419"},
                new BandeiraPadraoConst() { Nome = "TENNISBAR", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00420"},
                new BandeiraPadraoConst() { Nome = "MAIS MEGA LOJA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00421"},
                new BandeiraPadraoConst() { Nome = "SAITO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00422"},
                new BandeiraPadraoConst() { Nome = "DEMANOS DIMANOS", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00423"},
                new BandeiraPadraoConst() { Nome = "ELMO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00424"},
                new BandeiraPadraoConst() { Nome = "TESOURA DE OURO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00425"},
                new BandeiraPadraoConst() { Nome = "LOJAO DO BRAS", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00426"},
                new BandeiraPadraoConst() { Nome = "FREECENTER CALCADOS", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00427"},
                new BandeiraPadraoConst() { Nome = "MAGAZINE DA ECONOMIA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00428"},
                new BandeiraPadraoConst() { Nome = "POLYELLE", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00429"},
                new BandeiraPadraoConst() { Nome = "KATTAN", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00430"},
                new BandeiraPadraoConst() { Nome = "EMANUELLE PE", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00431"},
                new BandeiraPadraoConst() { Nome = "EMMANUELLE SE", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00432"},
                new BandeiraPadraoConst() { Nome = "KATUXA CALCADOS", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00433"},
                new BandeiraPadraoConst() { Nome = "GRIPPON SP", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00434"},
                new BandeiraPadraoConst() { Nome = "ESKALA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00435"},
                new BandeiraPadraoConst() { Nome = "DENY SPORTS", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00436"},
                new BandeiraPadraoConst() { Nome = "PRINCESA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00437"},
                new BandeiraPadraoConst() { Nome = "DEL FIORI", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00438"},
                new BandeiraPadraoConst() { Nome = "PAQUETA CALCADOS LT", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00439"},
                new BandeiraPadraoConst() { Nome = "3B", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00440"},
                new BandeiraPadraoConst() { Nome = "ROLDAO ATACADISTA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00441"},
                new BandeiraPadraoConst() { Nome = "ESTUDIO SHOES", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00442"},
                new BandeiraPadraoConst() { Nome = "PASSARELA MODAS", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00443"},
                new BandeiraPadraoConst() { Nome = "ITAPUA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00444"},
                new BandeiraPadraoConst() { Nome = "OBJETIVA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00445"},
                new BandeiraPadraoConst() { Nome = "PONTO MIX", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00446"},
                new BandeiraPadraoConst() { Nome = "CASA E VIDEO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00447"},
                new BandeiraPadraoConst() { Nome = "SONHO DOS PES", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00448"},
                new BandeiraPadraoConst() { Nome = "SAPATELLA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00449"},
                new BandeiraPadraoConst() { Nome = "COSTAZUL ALIMENTOS", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00451"},
                new BandeiraPadraoConst() { Nome = "SUPERPRIX", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00452"},
                new BandeiraPadraoConst() { Nome = "CAMPE", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00453"},
                new BandeiraPadraoConst() { Nome = "KIAB", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00454"},
                new BandeiraPadraoConst() { Nome = "FONSEC", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00455"},
                new BandeiraPadraoConst() { Nome = "SK", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00456"},
                new BandeiraPadraoConst() { Nome = "DI SANTINNI", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00457"},
                new BandeiraPadraoConst() { Nome = "HAKUO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00458"},
                new BandeiraPadraoConst() { Nome = "ZINZANE", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00459"},
                new BandeiraPadraoConst() { Nome = "TACO", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00460"},
                new BandeiraPadraoConst() { Nome = "EPA E", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00461"},
                new BandeiraPadraoConst() { Nome = "ALEGRIA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00462"},
                new BandeiraPadraoConst() { Nome = "REDE LITORAL", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00463"},
                new BandeiraPadraoConst() { Nome = "CAEDU", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00464"},
                new BandeiraPadraoConst() { Nome = "ZUKEN VIP", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00465"},
                new BandeiraPadraoConst() { Nome = "ECON CARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00466"},
                new BandeiraPadraoConst() { Nome = "KAWAKAMI", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00407"},
                new BandeiraPadraoConst() { Nome = "BELLO CARD", Tipo = "CREDITO", Codigo = "00467"},
                new BandeiraPadraoConst() { Nome = "BELLO CARD", Tipo = "DEBITO", Codigo = "20245"},
                new BandeiraPadraoConst() { Nome = "IDID", Tipo = "CARTEIRA DIGITAL", Codigo = "10353"},
                new BandeiraPadraoConst() { Nome = "CASH BERTI", Tipo = "CARTEIRA DIGITAL", Codigo = "10354"},
                new BandeiraPadraoConst() { Nome = "APTARE", Tipo = "CREDITO", Codigo = "00468"},
                new BandeiraPadraoConst() { Nome = "APTARE", Tipo = "DEBITO", Codigo = "20246"},
                new BandeiraPadraoConst() { Nome = "MIDWAY", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00469"},
                new BandeiraPadraoConst() { Nome = "MIDWAY VISA", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00471"},
                new BandeiraPadraoConst() { Nome = "MIDWAY VISA", Tipo = "DEBITO PRIVATE LABEL", Codigo = "20249"},
                new BandeiraPadraoConst() { Nome = "MIDWAY MASTERCARD", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00470"},
                new BandeiraPadraoConst() { Nome = "MIDWAY MASTERCARD", Tipo = "DEBITO PRIVATE LABEL", Codigo = "20248"},
                new BandeiraPadraoConst() { Nome = "TEUCARD", Tipo = "CREDITO", Codigo = "00472"},
                new BandeiraPadraoConst() { Nome = "UPI", Tipo = "CREDITO", Codigo = "00474"},
                new BandeiraPadraoConst() { Nome = "DAFITI", Tipo = "CREDITO PRIVATE LABEL", Codigo = "00475"},
                new BandeiraPadraoConst() { Nome = "DISCOVER", Tipo = "CREDITO", Codigo = "00476"},
                new BandeiraPadraoConst() { Nome = "PAY FACE", Tipo = "CARTEIRA DIGITAL", Codigo = "10374"},
                new BandeiraPadraoConst() { Nome = "FITCARD", Tipo = "DEBITO", Codigo = "20252"},
                new BandeiraPadraoConst() { Nome = "FITCARD", Tipo = "VOUCHER", Codigo = "10380"},
                new BandeiraPadraoConst() { Nome = "SOMAPAY", Tipo = "CREDITO", Codigo = "00478"},
                new BandeiraPadraoConst() { Nome = "BRACOV", Tipo = "DEBITO", Codigo = "20253"},
                new BandeiraPadraoConst() { Nome = "BRACOV", Tipo = "CREDITO", Codigo = "00479"},
                new BandeiraPadraoConst() { Nome = "VC +", Tipo = "CARTEIRA DIGITAL", Codigo = "00150001"},
                new BandeiraPadraoConst() { Nome = "NUCASH", Tipo = "CARTEIRA DIGITAL", Codigo = "00190002"},
                new BandeiraPadraoConst() { Nome = "VELOE", Tipo = "CARTEIRA DIGITAL", Codigo = "00200003"},
                new BandeiraPadraoConst() { Nome = "IZPAY", Tipo = "CARTEIRA DIGITAL", Codigo = "00210004"},
                new BandeiraPadraoConst() { Nome = "VEE", Tipo = "CARTEIRA DIGITAL", Codigo = "00260005"},
                new BandeiraPadraoConst() { Nome = "MERCADO PAGO", Tipo = "CARTEIRA DIGITAL", Codigo = "00290006"},
                new BandeiraPadraoConst() { Nome = "MONEYPAG", Tipo = "CARTEIRA DIGITAL", Codigo = "00300007"},
                new BandeiraPadraoConst() { Nome = "TROCO SIMPLES", Tipo = "CARTEIRA DIGITAL", Codigo = "00340008"},
                new BandeiraPadraoConst() { Nome = "ITAU", Tipo = "CARTEIRA DIGITAL", Codigo = "00380009"},
                new BandeiraPadraoConst() { Nome = "BEEVALE", Tipo = "CARTEIRA DIGITAL", Codigo = "00550010"},
                new BandeiraPadraoConst() { Nome = "BRINKSPAY", Tipo = "CARTEIRA DIGITAL", Codigo = "00580011"},
                new BandeiraPadraoConst() { Nome = "PICPAY", Tipo = "CARTEIRA DIGITAL", Codigo = "00600012"},
                new BandeiraPadraoConst() { Nome = "PAGSEGURO", Tipo = "CARTEIRA DIGITAL", Codigo = "00650013"},
                new BandeiraPadraoConst() { Nome = "CONNECTYPAY", Tipo = "CARTEIRA DIGITAL", Codigo = "00720021"},
                new BandeiraPadraoConst() { Nome = "AME DIGITAL", Tipo = "CARTEIRA DIGITAL", Codigo = "00760023"},
                new BandeiraPadraoConst() { Nome = "UPBRASIL", Tipo = "CARTEIRA DIGITAL", Codigo = "00810025"},
                new BandeiraPadraoConst() { Nome = "CASH BERTI", Tipo = "CARTEIRA DIGITAL", Codigo = "00860027"},
                new BandeiraPadraoConst() { Nome = "COMPROPAY", Tipo = "CARTEIRA DIGITAL", Codigo = "00870028"},
                new BandeiraPadraoConst() { Nome = "CONDUCTOR", Tipo = "CARTEIRA DIGITAL", Codigo = "01030037"},
                new BandeiraPadraoConst() { Nome = "PIX", Tipo = "CARTEIRA DIGITAL", Codigo = "60110024"},
                new BandeiraPadraoConst() { Nome = "PIX SAQUE", Tipo = "CARTEIRA DIGITAL", Codigo = "60110042"},
                new BandeiraPadraoConst() { Nome = "PIX TROCO", Tipo = "CARTEIRA DIGITAL", Codigo = "60110043"},
                new BandeiraPadraoConst() { Nome = "CIELO", Tipo = "CARTEIRA DIGITAL", Codigo = "80001000"},
                new BandeiraPadraoConst() { Nome = "TÁ PAGO", Tipo = "CARTEIRA DIGITAL", Codigo = "80021002"},
                new BandeiraPadraoConst() { Nome = "4ALL", Tipo = "CARTEIRA DIGITAL", Codigo = "80031003"},
                new BandeiraPadraoConst() { Nome = "MIDWAY", Tipo = "CARTEIRA DIGITAL", Codigo = "80051004"},
                new BandeiraPadraoConst() { Nome = "PAYFACE", Tipo = "CARTEIRA DIGITAL", Codigo = "00920030"},
                new BandeiraPadraoConst() { Nome = "RAPPI", Tipo = "CARTEIRA DIGITAL", Codigo = "00970034"},
                new BandeiraPadraoConst() { Nome = "MEU VALE", Tipo = "CARTEIRA DIGITAL", Codigo = "00660014"},
                new BandeiraPadraoConst() { Nome = "VERDE CARD", Tipo = "CARTEIRA DIGITAL", Codigo = "00120015"},
                new BandeiraPadraoConst() { Nome = "TROCO SIMPLES DOACAO", Tipo = "CARTEIRA DIGITAL", Codigo = "00340017"},
                new BandeiraPadraoConst() { Nome = "TICKETLOG", Tipo = "CARTEIRA DIGITAL", Codigo = "00040018"},
                new BandeiraPadraoConst() { Nome = "GOODCARD", Tipo = "CARTEIRA DIGITAL", Codigo = "00130019"},
                new BandeiraPadraoConst() { Nome = "ABM_CASH", Tipo = "CARTEIRA DIGITAL", Codigo = "00640020"},
                new BandeiraPadraoConst() { Nome = "SEM PARAR", Tipo = "CARTEIRA DIGITAL", Codigo = "00840026"},
                new BandeiraPadraoConst() { Nome = "QR PAGO", Tipo = "CARTEIRA DIGITAL", Codigo = "60120033"},
                new BandeiraPadraoConst() { Nome = "BANCO24HORAS", Tipo = "CARTEIRA DIGITAL", Codigo = "00980035"}
            };
        }
        public static BandeiraPadraoConst RetornarBandeiraPadrao(int _codigo)
        {
            return RetornarLista().Find(p => p.CodigoInt == _codigo);
        }
    }
}
